/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "pagespeed/system/admin_site.h"

#include <cstddef>
#include <memory>
#include <set>
#include <vector>

#include "net/instaweb/http/public/async_fetch.h"
#include "net/instaweb/http/public/http_cache.h"
#include "net/instaweb/rewriter/public/rewrite_options.h"
#include "net/instaweb/rewriter/public/server_context.h"
#include "net/instaweb/util/public/property_cache.h"
#include "net/instaweb/util/public/property_store.h"
#include "pagespeed/kernel/base/cache_interface.h"
#include "pagespeed/kernel/base/callback.h"
#include "pagespeed/kernel/base/message_handler.h"
#include "pagespeed/kernel/base/statistics.h"
#include "pagespeed/kernel/base/string.h"
#include "pagespeed/kernel/base/string_util.h"
#include "pagespeed/kernel/base/string_writer.h"
#include "pagespeed/kernel/base/timer.h"
#include "pagespeed/kernel/cache/purge_context.h"
#include "pagespeed/kernel/http/content_type.h"
#include "pagespeed/kernel/http/google_url.h"
#include "pagespeed/kernel/http/http_names.h"
#include "pagespeed/kernel/http/query_params.h"
#include "pagespeed/kernel/http/response_headers.h"
#include "pagespeed/kernel/util/statistics_logger.h"
#include "pagespeed/system/system_cache_path.h"
#include "pagespeed/system/admin_license_handler.h"
#include "pagespeed/system/system_caches.h"
#include "pagespeed/system/system_rewrite_options.h"

namespace net_instaweb {

// Embedded SPA console, generated by data2c from the Vite build output.
extern const char* HTML_admin_console;

namespace {

void WriteJsonResponse(AsyncFetch* fetch, StringPiece json_body,
                       Timer* timer, MessageHandler* handler) {
  fetch->response_headers()->SetStatusAndReason(HttpStatus::kOK);
  fetch->response_headers()->Add(HttpAttributes::kContentType,
                                 kContentTypeJson.mime_type());
  int64 now_ms = timer->NowMs();
  fetch->response_headers()->SetLastModified(now_ms);
  fetch->Write(json_body, handler);
  fetch->Done(true);
}

// Provides a Done(bool, StringPiece) entry point for use as a Purge
// callback. Translates the success into an Http status code for the
// AsyncFetch, sending any failure reason in the response body as JSON.
class PurgeFetchCallbackGasket {
 public:
  PurgeFetchCallbackGasket(AsyncFetch* fetch, Timer* timer,
                           MessageHandler* handler)
      : fetch_(fetch), timer_(timer), message_handler_(handler) {}
  void Done(bool success, StringPiece reason) {
    GoogleString json;
    if (success) {
      json = "{\"success\":true,\"message\":\"Purge successful\"}";
    } else {
      GoogleString escaped_reason = JsonEscape(reason);
      GoogleString escaped_error = JsonEscape(error_);
      json = StrCat("{\"success\":false,\"error\":\"", escaped_reason);
      if (!error_.empty()) {
        StrAppend(&json, " ", escaped_error);
      }
      StrAppend(&json, "\"}");
    }
    WriteJsonResponse(fetch_, json, timer_, message_handler_);
    delete this;
  }

  void set_error(StringPiece x) { x.CopyToString(&error_); }

 private:
  AsyncFetch* fetch_;
  Timer* timer_;
  MessageHandler* message_handler_;
  GoogleString error_;

  PurgeFetchCallbackGasket(const PurgeFetchCallbackGasket&) = delete;
  PurgeFetchCallbackGasket& operator=(const PurgeFetchCallbackGasket&) = delete;
};

}  // namespace

AdminSite::AdminSite(Timer* timer, ThreadSystem* thread_system,
                     MessageHandler* message_handler,
                     UrlAsyncFetcher* fetcher,
                     const GoogleString& cache_path)
    : message_handler_(message_handler),
      timer_(timer),
      license_handler_(
          new AdminLicenseHandler(timer, thread_system, message_handler,
                                 fetcher, cache_path)) {
  license_handler_->Init();
}

AdminSite::~AdminSite() = default;

void AdminSite::ServeSpaConsole(AsyncFetch* fetch) {
  ResponseHeaders* headers = fetch->response_headers();
  headers->SetStatusAndReason(HttpStatus::kOK);
  headers->Add(HttpAttributes::kContentType, "text/html");
  // Prevent PageSpeed from rewriting the admin console itself.
  headers->Add("PageSpeed", "off");
  headers->Add("Cache-Control", "no-cache");
  fetch->Write(HTML_admin_console, message_handler_);
  fetch->Done(true);
}

// Handler which serves PSOL console.
void AdminSite::ConsoleHandler(const SystemRewriteOptions& global_options,
                               const RewriteOptions& options,
                               AdminSource source,
                               const QueryParams& query_params,
                               AsyncFetch* fetch, Statistics* statistics) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
    return;
  }
  ServeSpaConsole(fetch);
}

void AdminSite::StatisticsJsonHandler(AsyncFetch* fetch, Statistics* stats) {
  fetch->response_headers()->SetStatusAndReason(HttpStatus::kOK);
  fetch->response_headers()->Add(HttpAttributes::kContentType,
                                 kContentTypeJson.mime_type());
  stats->DumpJson(fetch, message_handler_);
  fetch->Done(true);
}

void AdminSite::StatisticsJsonDump(AsyncFetch* fetch, Statistics* stats) {
  StatisticsJsonHandler(fetch, stats);
}

void AdminSite::StatisticsHandler(const RewriteOptions& options,
                                  AdminSource source, AsyncFetch* fetch,
                                  Statistics* stats) {
  // Delegate to StatisticsJsonHandler which returns JSON from stats->DumpJson.
  StatisticsJsonHandler(fetch, stats);
}

void AdminSite::GraphsHandler(const RewriteOptions& options, AdminSource source,
                              const QueryParams& query_params,
                              AsyncFetch* fetch, Statistics* statistics) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
    return;
  }
  ServeSpaConsole(fetch);
}

void AdminSite::ConsoleJsonHandler(const QueryParams& params, AsyncFetch* fetch,
                                   Statistics* statistics) {
  StatisticsLogger* console_logger = statistics->console_logger();
  if (console_logger == nullptr) {
    fetch->response_headers()->SetStatusAndReason(HttpStatus::kNotFound);
    fetch->response_headers()->Add(HttpAttributes::kContentType,
                                   kContentTypeJson.mime_type());
    fetch->Write(
        "{\"error\":\"console_logger must be enabled to use '?json' "
        "query parameter.\"}",
        message_handler_);
    fetch->Done(true);
    return;
  }

  fetch->response_headers()->SetStatusAndReason(HttpStatus::kOK);
  fetch->response_headers()->Add(HttpAttributes::kContentType,
                                 kContentTypeJson.mime_type());

  std::set<GoogleString> var_titles;
  // Default is to fetch data used on graphs page.
  bool dump_for_graphs = true;

  // Default values for start_time, end_time, and granularity_ms in case the
  // query does not include these parameters.
  int64 start_time = 0;
  int64 end_time = timer_->NowMs();
  // Granularity is the difference in ms between data points. If it is not
  // specified by the query, the default value is 3000 ms, the same as the
  // default logging granularity.
  int64 granularity_ms = 3000;
  for (int i = 0; i < params.size(); ++i) {
    GoogleString value;
    if (params.UnescapedValue(i, &value)) {
      StringPiece name = params.name(i);
      if (name == "start_time") {
        StringToInt64(value, &start_time);
      } else if (name == "end_time") {
        StringToInt64(value, &end_time);
      } else if (name == "var_titles") {
        // Fetch specified data if users populate var_titles.
        dump_for_graphs = false;
        std::vector<StringPiece> variable_names;
        SplitStringPieceToVector(value, ",", &variable_names, true);
        for (size_t i = 0; i < variable_names.size(); ++i) {
          var_titles.insert(variable_names[i].as_string());
        }
      } else if (name == "granularity") {
        StringToInt64(value, &granularity_ms);
      }
    }
  }
  console_logger->DumpJSON(dump_for_graphs, var_titles, start_time, end_time,
                            granularity_ms, fetch, message_handler_);
  fetch->Done(true);
}

void AdminSite::PrintHistograms(AdminSource source, AsyncFetch* fetch,
                                Statistics* stats) {
  GoogleString histogram_text;
  StringWriter writer(&histogram_text);
  stats->RenderHistograms(&writer, message_handler_);
  GoogleString json = StrCat("{\"histograms\":\"", JsonEscape(histogram_text),
                             "\"}");
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::PrintCaches(
    bool is_global, AdminSource source, const GoogleUrl& stripped_gurl,
    const QueryParams& query_params, const RewriteOptions* options,
    SystemCachePath* cache_path, AsyncFetch* fetch, SystemCaches* system_caches,
    CacheInterface* filesystem_metadata_cache, HTTPCache* http_cache,
    CacheInterface* metadata_cache, PropertyCache* page_property_cache,
    ServerContext* server_context) {
  GoogleString url;
  if ((source == kPageSpeedAdmin) &&
      query_params.Lookup1Unescaped("url", &url)) {
    // Delegate to ShowCacheHandler to get the cached value for that URL.
    // Always use JSON format now.
    GoogleString ua;
    query_params.Lookup1Unescaped("user_agent", &ua);
    server_context->ShowCacheHandler(
        ServerContext::kFormatAsJson, url, ua,
        query_params.Has("Delete"), fetch, options->Clone());
  } else if ((source == kPageSpeedAdmin) &&
             query_params.Lookup1Unescaped("new_set", &url)) {
    GoogleString purge_set = options->PurgeSetString();
    GoogleString json = StrCat("{\"purge_set\":\"", JsonEscape(purge_set),
                               "\"}");
    WriteJsonResponse(fetch, json, timer_, message_handler_);
  } else if ((source == kPageSpeedAdmin) &&
             query_params.Lookup1Unescaped("purge", &url)) {
    if (!options->enable_cache_purge()) {
      GoogleString json = StrCat(
          "{\"success\":false,\"error\":\"Purging not enabled: please add '",
          JsonEscape(server_context->FormatOption("EnableCachePurge", "on")),
          "' to your configuration file.\"}");
      WriteJsonResponse(fetch, json, timer_, message_handler_);
    } else if (url == "*") {
      PurgeHandler(url, cache_path, fetch);
    } else if (url.empty()) {
      WriteJsonResponse(
          fetch, "{\"success\":false,\"error\":\"Empty URL\"}",
          timer_, message_handler_);
    } else {
      GoogleUrl origin(stripped_gurl.Origin());
      GoogleUrl resolved(origin, url);
      if (!resolved.IsWebValid()) {
        GoogleString escaped_url = JsonEscape(url);
        GoogleString json = StrCat(
            "{\"success\":false,\"error\":\"Invalid URL: ", escaped_url, "\"}");
        WriteJsonResponse(fetch, json, timer_, message_handler_);
      } else {
        PurgeHandler(resolved.Spec(), cache_path, fetch);
      }
    }
  } else {
    // Return JSON with cache structure info.
    GoogleString json = "{\"caches\":[";
    const char* separator = "";

    // HTTP Cache
    StrAppend(&json, separator, "{\"name\":\"HTTP Cache\",\"summary\":\"",
              JsonEscape(http_cache->Name()), "\"}");
    separator = ",";

    // Metadata Cache
    StrAppend(&json, separator, "{\"name\":\"Metadata Cache\",\"summary\":\"",
              JsonEscape(metadata_cache->Name()), "\"}");

    // Property Cache
    StrAppend(&json, separator,
              "{\"name\":\"Property Cache\",\"summary\":\"",
              JsonEscape(page_property_cache->property_store()->Name()), "\"}");

    // FileSystem Metadata Cache
    GoogleString fsmdc_name =
        (filesystem_metadata_cache == nullptr)
            ? "none"
            : filesystem_metadata_cache->Name();
    StrAppend(&json, separator,
              "{\"name\":\"FileSystem Metadata Cache\",\"summary\":\"",
              JsonEscape(fsmdc_name), "\"}");

    json += "]";

    // Backend stats
    if (system_caches != nullptr) {
      int flags = SystemCaches::kDefaultStatFlags;
      if (is_global) {
        flags |= SystemCaches::kGlobalView;
      }
      flags |= SystemCaches::kIncludeMemcached;
      flags |= SystemCaches::kIncludeRedis;
      GoogleString backend_stats;
      system_caches->PrintCacheStats(
          static_cast<SystemCaches::StatFlags>(flags), &backend_stats);
      StrAppend(&json, ",\"backend_stats\":\"", JsonEscape(backend_stats),
                "\"");
    }

    // Purge enabled
    StrAppend(&json, ",\"purge_enabled\":",
              options->enable_cache_purge() ? "true" : "false");

    json += "}";
    WriteJsonResponse(fetch, json, timer_, message_handler_);
  }
}

void AdminSite::PrintConfig(
    AdminSource source, AsyncFetch* fetch,
    SystemRewriteOptions* global_system_rewrite_options) {
  GoogleString config_text = global_system_rewrite_options->OptionsToString();
  GoogleString json = StrCat("{\"config\":\"", JsonEscape(config_text), "\"}");
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::MessageHistoryHandler(const RewriteOptions& options,
                                      AdminSource source, AsyncFetch* fetch) {
  GoogleString log;
  StringWriter log_writer(&log);
  GoogleString json = "{\"messages\":[";
  if (message_handler_->Dump(&log_writer)) {
    StringPieceVector messages;
    message_handler_->ParseMessageDumpIntoMessages(log, &messages);
    const char* separator = "";
    for (int i = 0, size = messages.size(); i < size; ++i) {
      if (messages[i].length() > 0) {
        const char* severity = "info";
        switch (message_handler_->GetMessageType(messages[i])) {
          case kError:
            severity = "error";
            break;
          case kWarning:
            severity = "warning";
            break;
          case kFatal:
            severity = "fatal";
            break;
          default:
            severity = "info";
            break;
        }
        GoogleString reformatted =
            message_handler_->ReformatMessage(messages[i]).as_string();
        StrAppend(&json, separator, "{\"severity\":\"", severity,
                  "\",\"message\":\"", JsonEscape(reformatted), "\"}");
        separator = ",";
      }
    }
  }
  json += "]}";
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::AdminPage(
    bool is_global, const GoogleUrl& stripped_gurl,
    const QueryParams& query_params, const RewriteOptions* options,
    SystemCachePath* cache_path, AsyncFetch* fetch, SystemCaches* system_caches,
    CacheInterface* filesystem_metadata_cache, HTTPCache* http_cache,
    CacheInterface* metadata_cache, PropertyCache* page_property_cache,
    ServerContext* server_context, Statistics* statistics, Statistics* stats,
    SystemRewriteOptions* global_system_rewrite_options,
    StringPiece request_body) {
  // The handler is "pagespeed_admin", so we must dispatch off of
  // the remainder of the URL.
  StringPiece path = stripped_gurl.PathSansQuery();  // "/pagespeed_admin/foo"
  path = path.substr(1);                             // "pagespeed_admin/foo"

  // If there are no slashes at all in the path, redirect by adding a slash
  // so that relative references work.
  if (path.find('/') == StringPiece::npos) {
    ResponseHeaders* response_headers = fetch->response_headers();
    response_headers->SetStatusAndReason(HttpStatus::kMovedPermanently);
    GoogleString admin_with_slash = StrCat(stripped_gurl.AllExceptQuery(), "/");
    response_headers->Add(HttpAttributes::kLocation, admin_with_slash);
    response_headers->Add(HttpAttributes::kContentType,
                          kContentTypeJson.mime_type());
    GoogleString json = StrCat("{\"redirect\":\"", JsonEscape(admin_with_slash),
                               "\"}");
    fetch->Write(json, message_handler_);
    fetch->Done(true);
  } else {
    // Check for /v1/license/* API paths before leaf-based dispatch.
    // The full path sans query looks like "/pagespeed_admin/v1/license/status".
    StringPiece full_path = stripped_gurl.PathSansQuery();
    StringPiece::size_type license_pos = full_path.find("/v1/license/");
    if (license_pos != StringPiece::npos) {
      // Extract the API path starting from /v1/license/...
      StringPiece api_path = full_path.substr(license_pos);
      if (!license_handler_->HandleRequest(api_path, request_body, is_global,
                                            fetch)) {
        fetch->response_headers()->SetStatusAndReason(HttpStatus::kNotFound);
        fetch->response_headers()->Add(HttpAttributes::kContentType,
                                       kContentTypeJson.mime_type());
        GoogleString json = StrCat("{\"error\":\"Unknown license endpoint: ",
                                   JsonEscape(api_path), "\"}");
        fetch->Write(json, message_handler_);
        fetch->Done(true);
      }
      return;
    }
    StringPiece leaf = stripped_gurl.LeafSansQuery();
    if (leaf.empty()) {
      // Root path serves the SPA console.
      ServeSpaConsole(fetch);
    } else if (leaf == "statistics") {
      if (query_params.Has("json")) {
        ConsoleJsonHandler(query_params, fetch, statistics);
      } else {
        StatisticsHandler(*options, kPageSpeedAdmin, fetch, stats);
      }
    } else if (leaf == "stats_json") {
      StatisticsJsonHandler(fetch, stats);
    } else if (leaf == "graphs") {
      GraphsHandler(*options, kPageSpeedAdmin, query_params, fetch, statistics);
    } else if (leaf == "config") {
      PrintConfig(kPageSpeedAdmin, fetch, global_system_rewrite_options);
    } else if (leaf == "console") {
      ConsoleHandler(*global_system_rewrite_options, *options, kPageSpeedAdmin,
                     query_params, fetch, statistics);
    } else if (leaf == "message_history") {
      MessageHistoryHandler(*options, kPageSpeedAdmin, fetch);
    } else if (leaf == "cache") {
      PrintCaches(is_global, kPageSpeedAdmin, stripped_gurl, query_params,
                  options, cache_path, fetch, system_caches,
                  filesystem_metadata_cache, http_cache, metadata_cache,
                  page_property_cache, server_context);
    } else if (leaf == "histograms") {
      PrintHistograms(kPageSpeedAdmin, fetch, stats);
    } else {
      fetch->response_headers()->SetStatusAndReason(HttpStatus::kNotFound);
      fetch->response_headers()->Add(HttpAttributes::kContentType,
                                     kContentTypeJson.mime_type());
      GoogleString json = StrCat("{\"error\":\"Unknown admin page: ",
                                 JsonEscape(leaf), "\"}");
      fetch->Write(json, message_handler_);
      fetch->Done(true);
    }
  }
}

void AdminSite::StatisticsPage(
    bool is_global, const QueryParams& query_params,
    const RewriteOptions* options, AsyncFetch* fetch,
    SystemCaches* system_caches, CacheInterface* filesystem_metadata_cache,
    HTTPCache* http_cache, CacheInterface* metadata_cache,
    PropertyCache* page_property_cache, ServerContext* server_context,
    Statistics* statistics, Statistics* stats,
    SystemRewriteOptions* global_system_rewrite_options) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
  } else if (query_params.Has("config")) {
    PrintConfig(kStatistics, fetch, global_system_rewrite_options);
  } else if (query_params.Has("histograms")) {
    PrintHistograms(kStatistics, fetch, stats);
  } else if (query_params.Has("graphs")) {
    GraphsHandler(*options, kStatistics, query_params, fetch, statistics);
  } else if (query_params.Has("cache")) {
    GoogleUrl empty_url;
    PrintCaches(is_global, kStatistics, empty_url, query_params, options,
                nullptr,  // cache_path is not available from statistics page.
                fetch, system_caches, filesystem_metadata_cache, http_cache,
                metadata_cache, page_property_cache, server_context);
  } else {
    StatisticsHandler(*options, kStatistics, fetch, stats);
  }
}

void AdminSite::PurgeHandler(StringPiece url, SystemCachePath* cache_path,
                             AsyncFetch* fetch) {
  PurgeContext* purge_context = cache_path->purge_context();
  int64 now_ms = timer_->NowMs();
  PurgeFetchCallbackGasket* gasket =
      new PurgeFetchCallbackGasket(fetch, timer_, message_handler_);
  PurgeContext::PurgeCallback* callback =
      NewCallback(gasket, &PurgeFetchCallbackGasket::Done);
  if (strings::EndsWith(url, "*")) {
    purge_context->SetCachePurgeGlobalTimestampMs(now_ms, callback);
  } else {
    purge_context->AddPurgeUrl(url, now_ms, callback);
  }
}

}  // namespace net_instaweb
