/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "pagespeed/system/admin_site.h"

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <map>
#include <memory>
#include <set>
#include <utility>
#include <vector>

#include "net/instaweb/http/public/async_fetch.h"
#include "net/instaweb/http/public/http_cache.h"
#include "net/instaweb/rewriter/public/rewrite_options.h"
#include "net/instaweb/rewriter/public/server_context.h"
#include "net/instaweb/util/public/property_cache.h"
#include "net/instaweb/util/public/property_store.h"
#include "pagespeed/kernel/base/cache_interface.h"
#include "pagespeed/kernel/base/callback.h"
#include "pagespeed/kernel/base/md5_hasher.h"
#include "pagespeed/kernel/base/message_handler.h"
#include "pagespeed/kernel/base/statistics.h"
#include "pagespeed/kernel/base/string.h"
#include "pagespeed/kernel/base/string_util.h"
#include "pagespeed/kernel/base/string_writer.h"
#include "pagespeed/kernel/base/time_util.h"
#include "pagespeed/kernel/base/timer.h"
#include "pagespeed/kernel/cache/purge_context.h"
#include "pagespeed/kernel/http/content_type.h"
#include "pagespeed/kernel/http/google_url.h"
#include "pagespeed/kernel/http/http_names.h"
#include "pagespeed/kernel/http/query_params.h"
#include "pagespeed/kernel/http/request_headers.h"
#include "pagespeed/kernel/http/response_headers.h"
#include "pagespeed/kernel/util/statistics_logger.h"
#include "pagespeed/system/admin_daemon_handler.h"
#include "pagespeed/system/daemon_reader.h"
#include "pagespeed/system/system_cache_path.h"
#include "pagespeed/system/system_caches.h"
#include "pagespeed/system/system_rewrite_options.h"
#include "pagespeed/system/system_server_context.h"

namespace net_instaweb {

// Embedded SPA console, generated by data2c from the Vite build output.
extern const char* HTML_admin_console;

namespace {

void WriteJsonResponse(AsyncFetch* fetch, StringPiece json_body, Timer* timer,
                       MessageHandler* handler) {
  ResponseHeaders* headers = fetch->response_headers();
  headers->SetStatusAndReason(HttpStatus::kOK);
  headers->Add(HttpAttributes::kContentType, kContentTypeJson.mime_type());
  headers->Add(HttpAttributes::kCacheControl, "no-store, private");
  headers->Add("X-Content-Type-Options", "nosniff");
  fetch->Write(json_body, handler);
  fetch->Done(true);
}

void WriteJsonError(AsyncFetch* fetch, HttpStatus::Code status,
                    StringPiece error, MessageHandler* handler) {
  ResponseHeaders* headers = fetch->response_headers();
  headers->SetStatusAndReason(status);
  headers->Add(HttpAttributes::kContentType, kContentTypeJson.mime_type());
  headers->Add(HttpAttributes::kCacheControl, "no-store, private");
  headers->Add("X-Content-Type-Options", "nosniff");
  fetch->Write(
      StrCat("{\"success\":false,\"error\":\"", JsonEscape(error), "\"}"),
      handler);
  fetch->Done(true);
}

// State-changing cache actions come only from the console itself: POST plus
// the X-Requested-With header the SPA sends.  Returns true when the request
// passed; otherwise the response is already written.
bool GateCacheAction(AsyncFetch* fetch, MessageHandler* handler) {
  const RequestHeaders* req = fetch->request_headers();
  if (req == nullptr || req->method() != RequestHeaders::kPost) {
    fetch->response_headers()->Add(HttpAttributes::kAllow, "POST");
    WriteJsonError(fetch, HttpStatus::kMethodNotAllowed, "method not allowed",
                   handler);
    return false;
  }
  const char* xrw = req->Lookup1("X-Requested-With");
  if (xrw == nullptr || !StringCaseEqual(xrw, "XMLHttpRequest")) {
    WriteJsonError(fetch, HttpStatus::kForbidden,
                   "cross-origin request refused", handler);
    return false;
  }
  return true;
}

// A per-vhost console may only touch URLs of the host it serves.
bool TargetBelongsToRequestHost(const GoogleUrl& request_url,
                                const GoogleUrl& target) {
  return StringCaseEqual(request_url.Host(), target.Host());
}

// Renders a double as a bare JSON number, or the JSON literal null for a
// non-finite value (an empty histogram's percentiles are nan).
GoogleString Num(double x) {
  return std::isfinite(x) ? StrCat(x) : GoogleString("null");
}

const char* MessageLevelName(MessageType type) {
  switch (type) {
    case kError:
      return "error";
    case kWarning:
      return "warning";
    case kFatal:
      return "fatal";
    default:
      return "info";
  }
}

// A 429 in the shape of the other admin JSON errors.  HttpStatus has no
// constant for it (the daemon proxy writes it the same way).
void WriteJsonBusy(AsyncFetch* fetch, MessageHandler* handler) {
  ResponseHeaders* headers = fetch->response_headers();
  headers->set_status_code(429);
  headers->Add(HttpAttributes::kContentType, kContentTypeJson.mime_type());
  headers->Add(HttpAttributes::kCacheControl, "no-store, private");
  headers->Add("X-Content-Type-Options", "nosniff");
  fetch->Write("{\"success\":false,\"error\":\"busy\"}", handler);
  fetch->Done(true);
}

struct MessageGroup {
  const char* level = "info";
  GoogleString template_text;
  int64 count = 0;
  int64 recent = 0;
  int64 last_ms = 0;  // 0: no line of the group carried a readable time.
};

// The grouped answer over messages[first..]: one row per (level, template),
// newest first, at most kMaxGroupedMessageBytes in all.  A continuation line
// (no header) takes the time of the header line before it.  window_s <= 0
// means no window: no "window_s" and no "recent".
GoogleString GroupedMessagesJson(MessageHandler* handler,
                                 const StringPieceVector& messages,
                                 size_t first, int64 lines_written,
                                 int64 now_ms, int64 window_s) {
  std::map<std::pair<GoogleString, GoogleString>, MessageGroup> by_key;
  const int64 window_start_ms = now_ms - window_s * 1000;
  int64 current_ms = -1;
  for (size_t i = first; i < messages.size(); ++i) {
    if (messages[i].empty()) continue;
    const char* level = MessageLevelName(handler->GetMessageType(messages[i]));
    const StringPiece line = handler->ReformatMessage(messages[i]);
    const StringPiece body = MessageLineBody(line);
    if (body.size() < line.size()) current_ms = MessageLineTimeMs(line);
    GoogleString text = MessageTemplate(body);
    MessageGroup& group = by_key[std::make_pair(GoogleString(level), text)];
    if (group.count == 0) {
      group.level = level;
      group.template_text = std::move(text);
    }
    ++group.count;
    if (current_ms > group.last_ms) group.last_ms = current_ms;
    if (window_s > 0 && current_ms >= 0 && current_ms >= window_start_ms) {
      ++group.recent;
    }
  }
  std::vector<const MessageGroup*> rows;
  rows.reserve(by_key.size());
  for (const auto& entry : by_key) rows.push_back(&entry.second);
  std::sort(rows.begin(), rows.end(),
            [](const MessageGroup* a, const MessageGroup* b) {
              if (a->last_ms != b->last_ms) return a->last_ms > b->last_ms;
              if (a->count != b->count) return a->count > b->count;
              const int level_order = strcmp(a->level, b->level);
              if (level_order != 0) return level_order < 0;
              return a->template_text < b->template_text;
            });
  // Room for the envelope around the rows.
  const size_t budget = kMaxGroupedMessageBytes - 256;
  GoogleString groups;
  bool truncated = false;
  const char* separator = "";
  for (const MessageGroup* group : rows) {
    GoogleString row =
        StrCat(separator, "{\"level\":\"", group->level, "\",\"template\":\"",
               JsonEscape(group->template_text),
               "\",\"count\":", Integer64ToString(group->count),
               ",\"last_ms\":", Integer64ToString(group->last_ms));
    if (window_s > 0) {
      StrAppend(&row, ",\"recent\":", Integer64ToString(group->recent));
    }
    row += "}";
    if (groups.size() + row.size() > budget) {
      truncated = true;
      break;
    }
    groups += row;
    separator = ",";
  }
  GoogleString json = StrCat(
      "{\"scope\":\"process\",\"next\":", Integer64ToString(lines_written),
      ",\"now_ms\":", Integer64ToString(now_ms));
  if (window_s > 0) {
    StrAppend(&json, ",\"window_s\":", Integer64ToString(window_s));
  }
  StrAppend(&json, ",\"truncated\":", truncated ? "true" : "false",
            ",\"groups\":[", groups, "]}");
  return json;
}

// Provides a Done(bool, StringPiece) entry point for use as a Purge
// callback. Translates the success into an Http status code for the
// AsyncFetch, sending any failure reason in the response body as JSON.
class PurgeFetchCallbackGasket {
 public:
  PurgeFetchCallbackGasket(AsyncFetch* fetch, Timer* timer,
                           MessageHandler* handler)
      : fetch_(fetch), timer_(timer), message_handler_(handler) {}
  void Done(bool success, StringPiece reason) {
    GoogleString json;
    if (success) {
      json = "{\"success\":true,\"message\":\"Purge successful\"}";
    } else {
      GoogleString escaped_reason = JsonEscape(reason);
      GoogleString escaped_error = JsonEscape(error_);
      json = StrCat("{\"success\":false,\"error\":\"", escaped_reason);
      if (!error_.empty()) {
        StrAppend(&json, " ", escaped_error);
      }
      StrAppend(&json, "\"}");
    }
    WriteJsonResponse(fetch_, json, timer_, message_handler_);
    delete this;
  }

  void set_error(StringPiece x) { x.CopyToString(&error_); }

 private:
  AsyncFetch* fetch_;
  Timer* timer_;
  MessageHandler* message_handler_;
  GoogleString error_;

  PurgeFetchCallbackGasket(const PurgeFetchCallbackGasket&) = delete;
  PurgeFetchCallbackGasket& operator=(const PurgeFetchCallbackGasket&) = delete;
};

}  // namespace

AdminSite::AdminSite(Timer* timer, MessageHandler* message_handler,
                     DaemonReader* daemon_reader)
    : message_handler_(message_handler),
      timer_(timer),
      daemon_reader_(daemon_reader),
      daemon_handler_(new AdminDaemonHandler(daemon_reader, message_handler)) {}

AdminSite::~AdminSite() = default;

void AdminSite::ServeSpaConsole(AsyncFetch* fetch) {
  static const GoogleString* const kBundleEtag = [] {
    MD5Hasher hasher;
    return new GoogleString(
        StrCat("\"", hasher.Hash(HTML_admin_console), "\""));
  }();
  ResponseHeaders* headers = fetch->response_headers();
  const RequestHeaders* req = fetch->request_headers();
  const char* inm =
      req != nullptr ? req->Lookup1(HttpAttributes::kIfNoneMatch) : nullptr;
  headers->Add(HttpAttributes::kEtag, *kBundleEtag);
  headers->Add(HttpAttributes::kCacheControl, "no-cache, private");
  // Prevent PageSpeed from rewriting the admin console itself.
  headers->Add("PageSpeed", "off");
  if (inm != nullptr && *kBundleEtag == inm) {
    headers->SetStatusAndReason(HttpStatus::kNotModified);
    fetch->Done(true);
    return;
  }
  headers->SetStatusAndReason(HttpStatus::kOK);
  headers->Add(HttpAttributes::kContentType, "text/html; charset=utf-8");
  headers->Add("X-Content-Type-Options", "nosniff");
  headers->Add("X-Frame-Options", "DENY");
  headers->Add("Referrer-Policy", "no-referrer");
  headers->Add("Content-Security-Policy",
               "default-src 'self'; script-src 'self' 'unsafe-inline'; "
               "style-src 'self' 'unsafe-inline'; img-src 'self' data:; "
               "connect-src 'self'; frame-ancestors 'none'; base-uri 'none'");
  fetch->Write(HTML_admin_console, message_handler_);
  fetch->Done(true);
}

// Handler which serves PSOL console.
void AdminSite::ConsoleHandler(const SystemRewriteOptions& global_options,
                               const RewriteOptions& options,
                               AdminSource source,
                               const QueryParams& query_params,
                               AsyncFetch* fetch, Statistics* statistics) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
    return;
  }
  ServeSpaConsole(fetch);
}

void AdminSite::StatisticsJsonHandler(AsyncFetch* fetch, Statistics* stats,
                                      bool is_global, StringPiece host) {
  ResponseHeaders* headers = fetch->response_headers();
  headers->SetStatusAndReason(HttpStatus::kOK);
  headers->Add(HttpAttributes::kContentType, kContentTypeJson.mime_type());
  headers->Add(HttpAttributes::kCacheControl, "no-store, private");
  headers->Add("X-Content-Type-Options", "nosniff");
  stats->DumpJson(is_global ? "global" : "vhost", host, timer_->NowMs(), fetch,
                  message_handler_);
  fetch->Done(true);
}

void AdminSite::StatisticsHandler(const RewriteOptions& options,
                                  AdminSource source, AsyncFetch* fetch,
                                  Statistics* stats, bool is_global,
                                  StringPiece host) {
  // Delegate to StatisticsJsonHandler which returns JSON from stats->DumpJson.
  StatisticsJsonHandler(fetch, stats, is_global, host);
}

void AdminSite::GraphsHandler(const RewriteOptions& options, AdminSource source,
                              const QueryParams& query_params,
                              AsyncFetch* fetch, Statistics* statistics) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
    return;
  }
  ServeSpaConsole(fetch);
}

void AdminSite::ConsoleJsonHandler(const QueryParams& params, AsyncFetch* fetch,
                                   Statistics* statistics) {
  StatisticsLogger* console_logger = statistics->console_logger();
  if (console_logger == nullptr) {
    WriteJsonError(fetch, HttpStatus::kNotFound,
                   "console_logger must be enabled to use '?json' "
                   "query parameter.",
                   message_handler_);
    return;
  }

  ResponseHeaders* headers = fetch->response_headers();
  headers->SetStatusAndReason(HttpStatus::kOK);
  headers->Add(HttpAttributes::kContentType, kContentTypeJson.mime_type());
  headers->Add(HttpAttributes::kCacheControl, "no-store, private");
  headers->Add("X-Content-Type-Options", "nosniff");

  std::set<GoogleString> var_titles;
  // Default is to fetch data used on graphs page.
  bool dump_for_graphs = true;

  // Default values for start_time, end_time, and granularity_ms in case the
  // query does not include these parameters.
  int64 start_time = 0;
  int64 end_time = timer_->NowMs();
  // Granularity is the difference in ms between data points. If it is not
  // specified by the query, the default value is 3000 ms, the same as the
  // default logging granularity.
  int64 granularity_ms = 3000;
  for (int i = 0; i < params.size(); ++i) {
    GoogleString value;
    if (params.UnescapedValue(i, &value)) {
      StringPiece name = params.name(i);
      if (name == "start_time") {
        StringToInt64(value, &start_time);
      } else if (name == "end_time") {
        StringToInt64(value, &end_time);
      } else if (name == "var_titles") {
        // Fetch specified data if users populate var_titles.
        dump_for_graphs = false;
        std::vector<StringPiece> variable_names;
        SplitStringPieceToVector(value, ",", &variable_names, true);
        for (size_t i = 0; i < variable_names.size(); ++i) {
          var_titles.insert(variable_names[i].as_string());
        }
      } else if (name == "granularity") {
        StringToInt64(value, &granularity_ms);
      }
    }
  }
  console_logger->DumpJSON(dump_for_graphs, var_titles, start_time, end_time,
                           granularity_ms, fetch, message_handler_);
  fetch->Done(true);
}

void AdminSite::PrintHistograms(AdminSource source, AsyncFetch* fetch,
                                Statistics* stats) {
  GoogleString json = "{\"histograms\":[";
  const char* separator = "";
  const StringVector& names = stats->HistogramNames();
  for (const GoogleString& name : names) {
    Histogram* hist = stats->FindHistogram(name);
    if (hist == nullptr || hist->Count() == 0) continue;
    StrAppend(&json, separator, "{\"name\":\"", JsonEscape(name), "\"");
    StrAppend(&json, ",\"count\":",
              Integer64ToString(static_cast<int64>(hist->Count())),
              ",\"avg\":", Num(hist->Average()),
              ",\"stddev\":", Num(hist->StandardDeviation()));
    // Percentile estimates need a meaningful number of samples; with only a
    // handful they collapse onto a near-minimum bucket bound (e.g. -5000)
    // that is not a real latency/size value. Below the threshold, null the
    // four percentile fields rather than emit that no-data value.
    const bool show_percentiles =
        hist->Count() >= Histogram::kMinSamplesForPercentiles;
    StrAppend(&json, ",\"min\":", Num(hist->Minimum()),
              ",\"median\":", show_percentiles ? Num(hist->Median()) : "null",
              ",\"max\":", Num(hist->Maximum()));
    StrAppend(
        &json,
        ",\"p90\":", show_percentiles ? Num(hist->Percentile(90)) : "null",
        ",\"p95\":", show_percentiles ? Num(hist->Percentile(95)) : "null",
        ",\"p99\":", show_percentiles ? Num(hist->Percentile(99)) : "null",
        ",\"buckets\":[");
    const char* bsep = "";
    for (int i = 0, n = hist->NumBuckets(); i < n; ++i) {
      if (hist->BucketCount(i) == 0) continue;
      StrAppend(&json, bsep, "{\"start\":", Num(hist->BucketStart(i)),
                ",\"limit\":", Num(hist->BucketLimit(i)), ",\"count\":",
                Integer64ToString(static_cast<int64>(hist->BucketCount(i))),
                "}");
      bsep = ",";
    }
    json += "]}";
    separator = ",";
  }
  json += "]}";
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::PrintCaches(
    bool is_global, AdminSource source, const GoogleUrl& stripped_gurl,
    const QueryParams& query_params, const RewriteOptions* options,
    SystemCachePath* cache_path, AsyncFetch* fetch, SystemCaches* system_caches,
    CacheInterface* filesystem_metadata_cache, HTTPCache* http_cache,
    CacheInterface* metadata_cache, PropertyCache* page_property_cache,
    ServerContext* server_context) {
  GoogleString url;
  if ((source == kPageSpeedAdmin) &&
      query_params.Lookup1Unescaped("url", &url)) {
    if (query_params.Has("Delete") &&
        !GateCacheAction(fetch, message_handler_)) {
      return;
    }
    if (!is_global) {
      GoogleUrl target(url);
      if (!target.IsWebValid() ||
          !TargetBelongsToRequestHost(stripped_gurl, target)) {
        WriteJsonError(fetch, HttpStatus::kForbidden,
                       "URL belongs to another host; use that host's console",
                       message_handler_);
        return;
      }
    }
    // Delegate to ShowCacheHandler to get the cached value for that URL.
    // Always use JSON format now.
    GoogleString ua;
    query_params.Lookup1Unescaped("user_agent", &ua);
    server_context->ShowCacheHandler(ServerContext::kFormatAsJson, url, ua,
                                     query_params.Has("Delete"), fetch,
                                     options->Clone());
  } else if ((source == kPageSpeedAdmin) &&
             query_params.Lookup1Unescaped("new_set", &url)) {
    GoogleString purge_set = options->PurgeSetString();
    GoogleString json =
        StrCat("{\"purge_set\":\"", JsonEscape(purge_set), "\"}");
    WriteJsonResponse(fetch, json, timer_, message_handler_);
  } else if ((source == kPageSpeedAdmin) &&
             query_params.Lookup1Unescaped("purge", &url)) {
    if (!GateCacheAction(fetch, message_handler_)) {
      return;
    }
    // A per-vhost console is scoped to its own host: a whole-cache purge is
    // global-only, and a single-URL purge may only target this host.  These
    // scope checks run ahead of the "purge enabled" check below so a
    // disabled purge does not mask a cross-scope request as a soft failure.
    if (!is_global) {
      if (url == "*") {
        WriteJsonError(
            fetch, HttpStatus::kForbidden,
            "global purge is available from the global admin console",
            message_handler_);
        return;
      }
      if (!url.empty()) {
        GoogleUrl origin(stripped_gurl.Origin());
        GoogleUrl resolved(origin, url);
        if (resolved.IsWebValid()) {
          // PurgeHandler reads any target ending in '*' as the whole-cache
          // purge, whatever host the URL names; judge the resolved form, the
          // exact string the purge below would act on.
          if (strings::EndsWith(resolved.Spec(), "*")) {
            WriteJsonError(
                fetch, HttpStatus::kForbidden,
                "global purge is available from the global admin console",
                message_handler_);
            return;
          }
          if (!TargetBelongsToRequestHost(stripped_gurl, resolved)) {
            WriteJsonError(
                fetch, HttpStatus::kForbidden,
                "URL belongs to another host; use that host's console",
                message_handler_);
            return;
          }
        }
      }
    }
    if (!options->enable_cache_purge()) {
      GoogleString json = StrCat(
          "{\"success\":false,\"error\":\"Purging not enabled: please add '",
          JsonEscape(server_context->FormatOption("EnableCachePurge", "on")),
          "' to your configuration file.\"}");
      WriteJsonResponse(fetch, json, timer_, message_handler_);
    } else if (url == "*") {
      PurgeHandler(url, cache_path, fetch);
    } else if (url.empty()) {
      WriteJsonResponse(fetch, "{\"success\":false,\"error\":\"Empty URL\"}",
                        timer_, message_handler_);
    } else {
      GoogleUrl origin(stripped_gurl.Origin());
      GoogleUrl resolved(origin, url);
      if (!resolved.IsWebValid()) {
        GoogleString escaped_url = JsonEscape(url);
        GoogleString json = StrCat(
            "{\"success\":false,\"error\":\"Invalid URL: ", escaped_url, "\"}");
        WriteJsonResponse(fetch, json, timer_, message_handler_);
      } else {
        PurgeHandler(resolved.Spec(), cache_path, fetch);
      }
    }
  } else {
    // Return JSON with cache structure info.
    GoogleString json = "{\"caches\":[";
    const char* separator = "";

    // HTTP Cache
    StrAppend(&json, separator, "{\"name\":\"HTTP Cache\",\"summary\":\"",
              JsonEscape(http_cache->Name()), "\"}");
    separator = ",";

    // Metadata Cache
    StrAppend(&json, separator, "{\"name\":\"Metadata Cache\",\"summary\":\"",
              JsonEscape(metadata_cache->Name()), "\"}");

    // Property Cache
    StrAppend(&json, separator, "{\"name\":\"Property Cache\",\"summary\":\"",
              JsonEscape(page_property_cache->property_store()->Name()), "\"}");

    // FileSystem Metadata Cache
    GoogleString fsmdc_name = (filesystem_metadata_cache == nullptr)
                                  ? "none"
                                  : filesystem_metadata_cache->Name();
    StrAppend(&json, separator,
              "{\"name\":\"FileSystem Metadata Cache\",\"summary\":\"",
              JsonEscape(fsmdc_name), "\"}");

    json += "]";

    // Backend stats
    if (system_caches != nullptr) {
      GoogleString backend_stats;
      if (is_global) {
        int flags =
            SystemCaches::kDefaultStatFlags | SystemCaches::kGlobalView |
            SystemCaches::kIncludeMemcached | SystemCaches::kIncludeRedis;
        // Backend server status (memcached/redis) is a blocking per-server
        // query; only the aggregate console pays for it.
        system_caches->PrintCacheStats(
            static_cast<SystemCaches::StatFlags>(flags), &backend_stats);
      } else if (cache_path != nullptr) {
        // Per-vhost: only this vhost's own cache path. Never enumerate the
        // full set of declared caches here (see SystemCaches::PrintCacheStats).
        system_caches->PrintCachePathStats(cache_path, &backend_stats);
      }
      StrAppend(&json, ",\"backend_stats\":\"", JsonEscape(backend_stats),
                "\"");
    }

    // Purge enabled
    StrAppend(&json, ",\"purge_enabled\":",
              options->enable_cache_purge() ? "true" : "false");

    json += "}";
    WriteJsonResponse(fetch, json, timer_, message_handler_);
  }
}

void AdminSite::PrintConfig(AdminSource source, AsyncFetch* fetch,
                            const RewriteOptions& server_config,
                            const RewriteOptions& effective_options,
                            bool is_global, StringPiece host) {
  GoogleString json =
      StrCat("{\"config\":\"", JsonEscape(server_config.OptionsToString()),
             "\",\"effective_config\":\"",
             JsonEscape(effective_options.OptionsToString()), "\",\"scope\":\"",
             is_global ? "global" : "vhost", "\",\"host\":\"", JsonEscape(host),
             "\"}");
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::MessageHistoryHandler(const RewriteOptions& options,
                                      AdminSource source,
                                      const QueryParams& query_params,
                                      AsyncFetch* fetch) {
  // grouped=1: the same lines folded into one row per message template (see
  // GroupedMessagesJson).  Read-only and one at a time: it walks the whole
  // retained buffer.
  GoogleString grouped_str;
  const bool grouped = query_params.Lookup1Unescaped("grouped", &grouped_str) &&
                       grouped_str == "1";
  if (grouped) {
    const RequestHeaders* request = fetch->request_headers();
    const RequestHeaders::Method method =
        request != nullptr ? request->method() : RequestHeaders::kGet;
    if (method != RequestHeaders::kGet && method != RequestHeaders::kHead) {
      fetch->response_headers()->Add(HttpAttributes::kAllow, "GET, HEAD");
      WriteJsonError(fetch, HttpStatus::kMethodNotAllowed, "method not allowed",
                     message_handler_);
      return;
    }
    if (grouped_in_flight_.exchange(true, std::memory_order_acq_rel)) {
      WriteJsonBusy(fetch, message_handler_);
      return;
    }
  }
  int64 since = -1;
  GoogleString since_str;
  if (query_params.Lookup1Unescaped("since", &since_str)) {
    if (!StringToInt64(since_str, &since) || since < 0) {
      since = -1;
    }
  }
  GoogleString log;
  StringWriter log_writer(&log);
  int64 lines_written = 0;
  StringPieceVector messages;
  if (message_handler_->DumpWithCount(&log_writer, &lines_written)) {
    message_handler_->ParseMessageDumpIntoMessages(log, &messages);
  }
  // ParseMessageDumpIntoMessages always drops the first (possibly partial)
  // line, and every buffered line ends in "\n", so splitting always yields
  // one trailing empty entry too -- neither corresponds to a real line, so
  // `messages.size() - 1` ("real_slots") is comparable to `lines_written`
  // 1:1 (each split entry is exactly one line, and the counter now counts
  // lines, not Write() calls, so a multi-line message's lines are not
  // dropped or miscounted). Exclude that guaranteed trailing entry before
  // comparing the retained line count against how many lines are unseen; a
  // `since` older than what's retained (unseen >= real_slots) returns
  // everything retained.
  size_t first = 0;
  if (since >= 0 && since <= lines_written) {
    int64 unseen = lines_written - since;
    int64 real_slots = static_cast<int64>(messages.size()) - 1;
    if (unseen < real_slots) {
      first = static_cast<size_t>(real_slots - unseen);
    }
  }
  if (grouped) {
    // window_s: 1..kMaxMessageWindowSeconds; anything else means no window,
    // the same leniency `since` has.
    int64 window_s = -1;
    GoogleString window_str;
    if (query_params.Lookup1Unescaped("window_s", &window_str) &&
        (!StringToInt64(window_str, &window_s) || window_s < 1 ||
         window_s > kMaxMessageWindowSeconds)) {
      window_s = -1;
    }
    WriteJsonResponse(
        fetch,
        GroupedMessagesJson(message_handler_, messages, first, lines_written,
                            timer_->NowMs(), window_s),
        timer_, message_handler_);
    grouped_in_flight_.store(false, std::memory_order_release);
    return;
  }
  GoogleString json = StrCat(
      "{\"scope\":\"process\",\"next\":", Integer64ToString(lines_written),
      ",\"messages\":[");
  const char* separator = "";
  for (size_t i = first, size = messages.size(); i < size; ++i) {
    if (messages[i].empty()) continue;
    const char* severity = "info";
    switch (message_handler_->GetMessageType(messages[i])) {
      case kError:
        severity = "error";
        break;
      case kWarning:
        severity = "warning";
        break;
      case kFatal:
        severity = "fatal";
        break;
      default:
        severity = "info";
        break;
    }
    GoogleString reformatted =
        message_handler_->ReformatMessage(messages[i]).as_string();
    StrAppend(&json, separator, "{\"severity\":\"", severity,
              "\",\"message\":\"", JsonEscape(reformatted), "\"}");
    separator = ",";
  }
  json += "]}";
  WriteJsonResponse(fetch, json, timer_, message_handler_);
}

void AdminSite::AdminPage(
    bool is_global, const GoogleUrl& stripped_gurl,
    const QueryParams& query_params, const RewriteOptions* options,
    SystemCachePath* cache_path, AsyncFetch* fetch, SystemCaches* system_caches,
    CacheInterface* filesystem_metadata_cache, HTTPCache* http_cache,
    CacheInterface* metadata_cache, PropertyCache* page_property_cache,
    ServerContext* server_context, Statistics* statistics, Statistics* stats,
    SystemRewriteOptions* global_system_rewrite_options,
    StringPiece request_body, StringPiece own_serve_host) {
  // The handler is "pagespeed_admin", so we must dispatch off of
  // the remainder of the URL.
  StringPiece path = stripped_gurl.PathSansQuery();  // "/pagespeed_admin/foo"
  path = path.substr(1);                             // "pagespeed_admin/foo"

  // If there are no slashes at all in the path, redirect by adding a slash
  // so that relative references work.
  if (path.find('/') == StringPiece::npos) {
    ResponseHeaders* response_headers = fetch->response_headers();
    response_headers->SetStatusAndReason(HttpStatus::kMovedPermanently);
    GoogleString admin_with_slash = StrCat(stripped_gurl.AllExceptQuery(), "/");
    response_headers->Add(HttpAttributes::kLocation, admin_with_slash);
    response_headers->Add(HttpAttributes::kContentType,
                          kContentTypeJson.mime_type());
    response_headers->Add(HttpAttributes::kCacheControl, "no-store, private");
    response_headers->Add("X-Content-Type-Options", "nosniff");
    GoogleString json =
        StrCat("{\"redirect\":\"", JsonEscape(admin_with_slash), "\"}");
    fetch->Write(json, message_handler_);
    fetch->Done(true);
  } else {
    // The admin path may be mounted at any depth ("pagespeed_admin",
    // "alt/admin/path", ...), and the shared code cannot know that depth:
    // Apache, for one, does not expose the <Location> prefix a request
    // matched.  So dispatch is anchored on the tail of the path:
    //   - a trailing slash (empty last segment) is the SPA console root;
    //   - "v1/daemon/<leaf>" or "v1/daemon/<a>/<b>" at the end of the path
    //     is the read-only daemon proxy (leaf "<leaf>" or "<a>/<b>");
    //   - otherwise the last segment is the admin leaf.
    StringPieceVector segments;
    SplitStringPieceToVector(path, "/", &segments, false /* omit_empty */);
    const StringPiece leaf = segments.back();
    if (leaf.empty()) {
      // Root path serves the SPA console.
      ServeSpaConsole(fetch);
      return;
    }
    // /v1/daemon/* -- read-only proxy to the optimizer daemon's management
    // API.  Anchored on the tail like the rest of this dispatch: the
    // daemon leaf is the one or two segments directly after a
    // "v1/daemon" pair ("health", "cache/urls").  It is exact-matched
    // against AdminDaemonHandler's compile-time endpoint table: the
    // upstream path comes from the table, never from the request.  A
    // non-matching leaf gets a 404 here and never falls through to the
    // leaf-based dispatch below (so e.g. "v1/daemon/config" cannot
    // reach the module's config dump).
    const size_t n = segments.size();
    GoogleString daemon_leaf;
    bool is_daemon_request = false;
    if (n >= 3 && segments[n - 3] == "v1" && segments[n - 2] == "daemon") {
      segments[n - 1].CopyToString(&daemon_leaf);
      is_daemon_request = true;
    } else if (n >= 4 && segments[n - 4] == "v1" &&
               segments[n - 3] == "daemon") {
      daemon_leaf = StrCat(segments[n - 2], "/", segments[n - 1]);
      is_daemon_request = true;
    }
    if (is_daemon_request) {
      if (!daemon_handler_->HandleRequest(daemon_leaf, query_params, is_global,
                                          own_serve_host, fetch)) {
        // HandleRequest() never touched fetch, so this 404 -- the one
        // daemon-proxy response written here rather than by
        // AdminDaemonHandler -- is composed directly instead of through
        // the generic WriteJsonError, so the handler's own
        // AddProxyResponseHeaders can supply the same three headers every
        // other daemon-proxy response carries without adding
        // Cache-Control/X-Content-Type-Options a second time (WriteJsonError
        // already adds those on every other admin error path and must not
        // gain this proxy-only header).
        ResponseHeaders* headers = fetch->response_headers();
        headers->SetStatusAndReason(HttpStatus::kNotFound);
        headers->Add(HttpAttributes::kContentType,
                     kContentTypeJson.mime_type());
        AdminDaemonHandler::AddProxyResponseHeaders(headers);
        fetch->Write(
            StrCat("{\"success\":false,\"error\":\"",
                   JsonEscape(StrCat("Unknown daemon endpoint: ", daemon_leaf)),
                   "\"}"),
            message_handler_);
        fetch->Done(true);
      }
      return;
    }
    if (leaf == "statistics") {
      if (query_params.Has("json")) {
        ConsoleJsonHandler(query_params, fetch, statistics);
      } else {
        StatisticsHandler(*options, kPageSpeedAdmin, fetch, stats, is_global,
                          static_cast<SystemServerContext*>(server_context)
                              ->hostname_identifier());
      }
    } else if (leaf == "stats_json") {
      StatisticsJsonHandler(fetch, stats, is_global,
                            static_cast<SystemServerContext*>(server_context)
                                ->hostname_identifier());
    } else if (leaf == "graphs") {
      GraphsHandler(*options, kPageSpeedAdmin, query_params, fetch, statistics);
    } else if (leaf == "config") {
      PrintConfig(kPageSpeedAdmin, fetch, *global_system_rewrite_options,
                  *options, is_global,
                  static_cast<SystemServerContext*>(server_context)
                      ->hostname_identifier());
    } else if (leaf == "console") {
      ConsoleHandler(*global_system_rewrite_options, *options, kPageSpeedAdmin,
                     query_params, fetch, statistics);
    } else if (leaf == "message_history") {
      MessageHistoryHandler(*options, kPageSpeedAdmin, query_params, fetch);
    } else if (leaf == "cache") {
      PrintCaches(is_global, kPageSpeedAdmin, stripped_gurl, query_params,
                  options, cache_path, fetch, system_caches,
                  filesystem_metadata_cache, http_cache, metadata_cache,
                  page_property_cache, server_context);
    } else if (leaf == "histograms") {
      PrintHistograms(kPageSpeedAdmin, fetch, stats);
    } else {
      WriteJsonError(fetch, HttpStatus::kNotFound,
                     StrCat("Unknown admin page: ", leaf), message_handler_);
    }
  }
}

void AdminSite::StatisticsPage(
    bool is_global, const QueryParams& query_params,
    const RewriteOptions* options, AsyncFetch* fetch,
    SystemCaches* system_caches, CacheInterface* filesystem_metadata_cache,
    HTTPCache* http_cache, CacheInterface* metadata_cache,
    PropertyCache* page_property_cache, ServerContext* server_context,
    Statistics* statistics, Statistics* stats,
    SystemRewriteOptions* global_system_rewrite_options) {
  if (query_params.Has("json")) {
    ConsoleJsonHandler(query_params, fetch, statistics);
  } else if (query_params.Has("config")) {
    PrintConfig(kStatistics, fetch, *global_system_rewrite_options, *options,
                is_global,
                static_cast<SystemServerContext*>(server_context)
                    ->hostname_identifier());
  } else if (query_params.Has("histograms")) {
    PrintHistograms(kStatistics, fetch, stats);
  } else if (query_params.Has("graphs")) {
    GraphsHandler(*options, kStatistics, query_params, fetch, statistics);
  } else if (query_params.Has("cache")) {
    GoogleUrl empty_url;
    PrintCaches(is_global, kStatistics, empty_url, query_params, options,
                nullptr,  // cache_path is not available from statistics page.
                fetch, system_caches, filesystem_metadata_cache, http_cache,
                metadata_cache, page_property_cache, server_context);
  } else {
    StatisticsHandler(*options, kStatistics, fetch, stats, is_global,
                      static_cast<SystemServerContext*>(server_context)
                          ->hostname_identifier());
  }
}

void AdminSite::PurgeHandler(StringPiece url, SystemCachePath* cache_path,
                             AsyncFetch* fetch) {
  PurgeContext* purge_context = cache_path->purge_context();
  int64 now_ms = timer_->NowMs();
  PurgeFetchCallbackGasket* gasket =
      new PurgeFetchCallbackGasket(fetch, timer_, message_handler_);
  PurgeContext::PurgeCallback* callback =
      NewCallback(gasket, &PurgeFetchCallbackGasket::Done);
  if (strings::EndsWith(url, "*")) {
    purge_context->SetCachePurgeGlobalTimestampMs(now_ms, callback);
  } else {
    purge_context->AddPurgeUrl(url, now_ms, callback);
  }
}

// =============================================================================
// Defense-in-depth: warn once per handler family if a non-loopback client
// reaches one of the admin endpoints.  The deploying admin is expected to
// gate /pagespeed_admin/* (and friends) at the web-server / WAF layer.  If
// that gate is misconfigured or bypassed, we want a loud, one-shot signal
// in the error log.  We never block — operators may have legitimately widened
// access (CDN admin IP, ops VLAN); blocking would be wrong.
// =============================================================================
namespace {

// One std::atomic<bool> per AdminHandlerFamily.  Flipped from false→true the
// first time we log for that family; subsequent calls short-circuit.  Cleared
// at process start (default-initialised to false).
std::atomic<bool> g_admin_exposure_warned[static_cast<size_t>(
    AdminHandlerFamily::kNumFamilies)] = {};

}  // namespace

bool IsLoopbackClientIp(StringPiece client_ip) {
  if (client_ip.empty()) {
    // Caller couldn't determine — treat as non-loopback so the warning fires.
    return false;
  }
  if (client_ip == "localhost") {
    return true;
  }
  if (client_ip == "::1") {
    return true;
  }
  // IPv4-mapped or IPv4-compatible IPv6 loopback: ::ffff:127.x.y.z or
  // ::127.x.y.z.  Just check the textual suffix after the last colon — if the
  // resulting prefix is in the IPv4 loopback block (127.0.0.0/8) and the
  // earlier parts contain only "0"s, "ffff", or colons, accept.
  StringPiece::size_type last_colon = client_ip.rfind(':');
  StringPiece v4_part = client_ip;
  if (last_colon != StringPiece::npos) {
    StringPiece prefix = client_ip.substr(0, last_colon);
    // Normalise: only allow IPv4-mapped/compatible IPv6 — prefix must be one
    // of "::ffff", "::ffff:0:0", "::", "0:0:0:0:0:0", "0:0:0:0:0:ffff", etc.
    // Conservative check: prefix matches /^[0:f]+$/ (only zeros, colons, 'f').
    for (char c : prefix) {
      if (c != '0' && c != ':' && c != 'f' && c != 'F') {
        return false;
      }
    }
    v4_part = client_ip.substr(last_colon + 1);
  }
  // v4_part must be a dotted-quad starting with "127.".  We do a string
  // check rather than full IPv4 parse — first octet "127" is enough for
  // 127.0.0.0/8 loopback recognition, matching the LoopbackRouteFetcher
  // semantics.
  if (v4_part.starts_with("127.")) {
    // Sanity: ensure the rest is digits+dots, no embedded whitespace etc.
    for (char c : v4_part) {
      if (c != '.' && (c < '0' || c > '9')) {
        return false;
      }
    }
    return true;
  }
  return false;
}

void WarnIfNonLoopbackAdminAccess(StringPiece client_ip,
                                  AdminHandlerFamily family,
                                  StringPiece handler_name,
                                  MessageHandler* message_handler) {
  if (IsLoopbackClientIp(client_ip)) {
    return;
  }
  size_t idx = static_cast<size_t>(family);
  if (idx >= static_cast<size_t>(AdminHandlerFamily::kNumFamilies)) {
    return;
  }
  // CAS false→true; only the first arrival logs.
  bool expected = false;
  if (!g_admin_exposure_warned[idx].compare_exchange_strong(
          expected, true, std::memory_order_relaxed)) {
    return;
  }
  if (message_handler == nullptr) {
    return;
  }
  // Display "(unknown)" if the port couldn't supply a client IP — still useful
  // to operators (means the handler ran at all, which is itself the signal).
  GoogleString ip_for_log(client_ip.empty() ? StringPiece("(unknown)")
                                            : client_ip);
  GoogleString name_for_log(handler_name.empty() ? StringPiece("(unknown)")
                                                 : handler_name);
  message_handler->Message(
      kWarning,
      "mod_pagespeed: admin handler '%s' received request from %s; "
      "intended for loopback. Restrict access at the web-server layer "
      "(Apache: <Location> Require local; nginx: allow 127.0.0.1; deny all; "
      "IIS: InfoUrlsLocalOnly). See "
      "https://www.modpagespeed.com/1.1/docs/admin-console/"
      "#url-path-acls-are-brittle",
      name_for_log.c_str(), ip_for_log.c_str());
}

void ResetAdminExposureWarningsForTesting() {
  for (size_t i = 0; i < static_cast<size_t>(AdminHandlerFamily::kNumFamilies);
       ++i) {
    g_admin_exposure_warned[i].store(false, std::memory_order_relaxed);
  }
}

// =============================================================================
// Message templates (see admin_site.h).  Byte-level, ASCII character classes
// only, so the TypeScript twin in the admin console (which walks UTF-16 code
// units) produces the same text for any input: every non-ASCII byte is copied
// as it is.
// =============================================================================
// The character classes are the kernel's ASCII-only IsDecimalDigit,
// IsHexDigit and IsAsciiAlphaNumeric (string_util.h).
namespace {

// Characters that end a URL inside a message.
bool EndsUrl(char c) {
  return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '"' ||
         c == '\'' || c == '<' || c == '>' || c == '`';
}

bool AllAsciiDigits(StringPiece s) {
  if (s.empty()) return false;
  for (char c : s) {
    if (!IsDecimalDigit(c)) return false;
  }
  return true;
}

// "0x1f" style, or at least 8 hex digits mixing digits and letters.
bool IsHexId(StringPiece word) {
  if (word.size() >= 3 && word[0] == '0' &&
      (word[1] == 'x' || word[1] == 'X')) {
    bool all_hex = true;
    for (size_t i = 2; i < word.size(); ++i) {
      if (!IsHexDigit(word[i])) {
        all_hex = false;
        break;
      }
    }
    if (all_hex) return true;
  }
  if (word.size() < 8) return false;
  bool digit = false;
  bool letter = false;
  for (char c : word) {
    if (!IsHexDigit(c)) return false;
    if (IsDecimalDigit(c)) {
      digit = true;
    } else {
      letter = true;
    }
  }
  return digit && letter;
}

// Moves *rest past a leading "[<text without ']'>] " and returns the text.
bool TakeBracketGroup(StringPiece* rest, StringPiece* inside) {
  if (rest->empty() || (*rest)[0] != '[') return false;
  const size_t close = rest->find(']');
  if (close == StringPiece::npos || close + 1 >= rest->size() ||
      (*rest)[close + 1] != ' ') {
    return false;
  }
  *inside = rest->substr(1, close - 1);
  rest->remove_prefix(close + 2);
  return true;
}

bool IsMessageLevelName(StringPiece s) {
  return s == "Info" || s == "Warning" || s == "Error" || s == "Fatal";
}

// "<file>:<line>": split at the last colon, a non-empty file without spaces
// and a line of digits.
bool IsFileAndLine(StringPiece s) {
  const size_t colon = s.rfind(':');
  if (colon == StringPiece::npos || colon == 0) return false;
  for (size_t i = 0; i < colon; ++i) {
    if (s[i] == ' ') return false;
  }
  return AllAsciiDigits(s.substr(colon + 1));
}

// Moves *rest past "[<time>] [<Level>] " and returns the time text.
bool TakeMessageHeader(StringPiece* rest, StringPiece* time_text) {
  StringPiece after = *rest;
  StringPiece level;
  if (!TakeBracketGroup(&after, time_text) ||
      !TakeBracketGroup(&after, &level) || !IsMessageLevelName(level)) {
    return false;
  }
  *rest = after;
  return true;
}

}  // namespace

StringPiece MessageLineBody(StringPiece line) {
  StringPiece rest = line;
  StringPiece time_text;
  if (!TakeMessageHeader(&rest, &time_text)) return line;
  StringPiece after_pid = rest;
  StringPiece group;
  if (TakeBracketGroup(&after_pid, &group) && AllAsciiDigits(group)) {
    rest = after_pid;
    StringPiece after_file = rest;
    if (TakeBracketGroup(&after_file, &group) && IsFileAndLine(group)) {
      rest = after_file;
    }
  }
  return rest;
}

int64 MessageLineTimeMs(StringPiece line) {
  StringPiece rest = line;
  StringPiece time_text;
  int64 time_ms = 0;
  if (!TakeMessageHeader(&rest, &time_text) ||
      !ConvertStringToTime(time_text, &time_ms)) {
    return -1;
  }
  return time_ms;
}

GoogleString MessageTemplate(StringPiece body) {
  GoogleString out;
  out.reserve(body.size());
  const size_t n = body.size();
  size_t i = 0;
  while (i < n) {
    const char c = body[i];
    if ((c == 'h' || c == 'H') &&
        (StringCaseStartsWith(body.substr(i), "http://") ||
         StringCaseStartsWith(body.substr(i), "https://"))) {
      size_t j = i;
      while (j < n && !EndsUrl(body[j])) ++j;
      out.append("URL");
      i = j;
    } else if (IsAsciiAlphaNumeric(c)) {
      size_t j = i;
      while (j < n && IsAsciiAlphaNumeric(body[j])) ++j;
      const StringPiece word = body.substr(i, j - i);
      if (IsHexId(word)) {
        out.append("ID");
      } else {
        size_t k = 0;
        while (k < word.size()) {
          if (IsDecimalDigit(word[k])) {
            while (k < word.size() && IsDecimalDigit(word[k])) ++k;
            out.push_back('N');
          } else {
            out.push_back(word[k]);
            ++k;
          }
        }
      }
      i = j;
    } else {
      out.push_back(c);
      ++i;
    }
  }
  while (!out.empty() &&
         (out.back() == ' ' || out.back() == '\t' || out.back() == '\r')) {
    out.pop_back();
  }
  return out;
}

}  // namespace net_instaweb
