libjpeg_turbo_build_rule = """
cc_library(
    name = "libjpeg_headers",
    hdrs = [
        "src/jconfig.h",
        "src/jdct.h",
        "src/jerror.h",
        "src/jinclude.h",
        "src/jmorecfg.h",
        "src/jpeglib.h",
        "src/jpeglibmangler.h",
    ],
    includes = ["src"],
    visibility = ["//visibility:public"],
)

# 16-bit JPEG support (lossless only).
# Same sources as 8-bit subset, compiled with -DBITS_IN_JSAMPLE=16.
cc_library(
    name = "libjpeg16",
    srcs = [
        "src/jcapistd.c",
        "src/jccolor.c",
        "src/jcdiffct.c",
        "src/jclossls.c",
        "src/jcmainct.c",
        "src/jcprepct.c",
        "src/jcsample.c",
        "src/jdapistd.c",
        "src/jdcolor.c",
        "src/jddiffct.c",
        "src/jdlossls.c",
        "src/jdmainct.c",
        "src/jdpostct.c",
        "src/jdsample.c",
        "src/jutils.c",
    ],
    hdrs = [
        "src/cmyk.h",
        "src/jchuff.h",
        "src/jcmaster.h",
        "src/jconfigint.h",
        "src/jdcoefct.h",
        "src/jdmainct.h",
        "src/jdmaster.h",
        "src/jdmerge.h",
        "src/jdhuff.h",
        "src/jdsample.h",
        "src/jlossls.h",
        "src/jmemsys.h",
        "src/jpeg_nbits.h",
        "src/jpegapicomp.h",
        "src/jpegint.h",
        "src/jsamplecomp.h",
        "src/jsimd.h",
        "src/jsimddct.h",
        "src/jversion.h",
        "src/jccolext.c",
        "src/jdcol565.c",
        "src/jdcolext.c",
        "src/jdmrg565.c",
        "src/jdmrgext.c",
        "src/jstdhuff.c",
    ],
    copts = ["-DBITS_IN_JSAMPLE=16", "-DNO_GETENV", "-DNO_PUTENV"],
    includes = ["src"],
    deps = [":libjpeg_headers"],
)

# 12-bit JPEG support (lossy + lossless).
# Same as 16-bit plus DCT/quantization sources.
cc_library(
    name = "libjpeg12",
    srcs = [
        "src/jcapistd.c",
        "src/jccoefct.c",
        "src/jccolor.c",
        "src/jcdctmgr.c",
        "src/jcdiffct.c",
        "src/jclossls.c",
        "src/jcmainct.c",
        "src/jcprepct.c",
        "src/jcsample.c",
        "src/jdapistd.c",
        "src/jdcoefct.c",
        "src/jdcolor.c",
        "src/jddctmgr.c",
        "src/jddiffct.c",
        "src/jdlossls.c",
        "src/jdmainct.c",
        "src/jdmerge.c",
        "src/jdpostct.c",
        "src/jdsample.c",
        "src/jfdctfst.c",
        "src/jfdctint.c",
        "src/jidctflt.c",
        "src/jidctfst.c",
        "src/jidctint.c",
        "src/jidctred.c",
        "src/jquant1.c",
        "src/jquant2.c",
        "src/jutils.c",
    ],
    hdrs = [
        "src/cmyk.h",
        "src/jchuff.h",
        "src/jcmaster.h",
        "src/jconfigint.h",
        "src/jdcoefct.h",
        "src/jdmainct.h",
        "src/jdmaster.h",
        "src/jdmerge.h",
        "src/jdhuff.h",
        "src/jdsample.h",
        "src/jlossls.h",
        "src/jmemsys.h",
        "src/jpeg_nbits.h",
        "src/jpegapicomp.h",
        "src/jpegint.h",
        "src/jsamplecomp.h",
        "src/jsimd.h",
        "src/jsimddct.h",
        "src/jversion.h",
        "src/jccolext.c",
        "src/jdcol565.c",
        "src/jdcolext.c",
        "src/jdmrg565.c",
        "src/jdmrgext.c",
        "src/jstdhuff.c",
    ],
    copts = ["-DBITS_IN_JSAMPLE=12", "-DNO_GETENV", "-DNO_PUTENV"],
    includes = ["src"],
    deps = [":libjpeg_headers"],
)

cc_library(
    name = "libjpeg",
    srcs = [
        "src/jcapimin.c",
        "src/jcapistd.c",
        "src/jccoefct.c",
        "src/jccolor.c",
        "src/jcdctmgr.c",
        "src/jcdiffct.c",
        "src/jchuff.c",
        "src/jcicc.c",
        "src/jcinit.c",
        "src/jclhuff.c",
        "src/jclossls.c",
        "src/jcmainct.c",
        "src/jcmarker.c",
        "src/jcmaster.c",
        "src/jcomapi.c",
        "src/jcparam.c",
        "src/jcphuff.c",
        "src/jcprepct.c",
        "src/jcsample.c",
        "src/jctrans.c",
        "src/jdapimin.c",
        "src/jdapistd.c",
        "src/jdatadst.c",
        "src/jdatasrc.c",
        "src/jdcoefct.c",
        "src/jdcolor.c",
        "src/jddctmgr.c",
        "src/jddiffct.c",
        "src/jdhuff.c",
        "src/jdicc.c",
        "src/jdinput.c",
        "src/jdlhuff.c",
        "src/jdlossls.c",
        "src/jdmainct.c",
        "src/jdmarker.c",
        "src/jdmaster.c",
        "src/jdmerge.c",
        "src/jdphuff.c",
        "src/jdpostct.c",
        "src/jdsample.c",
        "src/jdtrans.c",
        "src/jerror.c",
        "src/jfdctflt.c",
        "src/jfdctfst.c",
        "src/jfdctint.c",
        "src/jidctflt.c",
        "src/jidctfst.c",
        "src/jidctint.c",
        "src/jidctred.c",
        "src/jmemmgr.c",
        "src/jmemnobs.c",
        "src/jpeg_nbits.c",
        "src/jquant1.c",
        "src/jquant2.c",
        "src/jutils.c",
    ],
    hdrs = [
        "src/cmyk.h",
        "src/jchuff.h",
        "src/jcmaster.h",
        "src/jconfigint.h",
        "src/jdcoefct.h",
        "src/jdmainct.h",
        "src/jdmaster.h",
        "src/jdmerge.h",
        "src/jdhuff.h",
        "src/jdsample.h",
        "src/jlossls.h",
        "src/jmemsys.h",
        "src/jpeg_nbits.h",
        "src/jpegapicomp.h",
        "src/jpegint.h",
        "src/jsamplecomp.h",
        "src/jsimd.h",
        "src/jsimddct.h",
        "src/jversion.h",
        # .c files included by other .c files (not compiled directly)
        "src/jccolext.c",
        "src/jdcol565.c",
        "src/jdcolext.c",
        "src/jdmrg565.c",
        "src/jdmrgext.c",
        "src/jstdhuff.c",
    ],
    copts = ["-DNO_GETENV", "-DNO_PUTENV"],
    includes = ["src"],
    deps = [
        ":libjpeg_headers",
        ":libjpeg12",
        ":libjpeg16",
    ],
    visibility = ["//visibility:public"],
)

"""
