# Bazel build for libpsl (https://github.com/rockdaboot/libpsl), the maintained
# Public Suffix List library that replaces the dead Apache-incubator
# domain_registry_provider ("drp"). See pagespeed/kernel/http/domain_registry.cc.
#
# Lean configuration goals:
#   * Builtin (compiled-in) PSL data only  -> ENABLE_BUILTIN, generated by the
#     bundled psl-make-dafsa python script from list/public_suffix_list.dat
#     (mirrors how drp generated its registry table via a genrule).
#   * No IDNA runtime backend (no ICU / libidn2 / libidn / libunistring) so we
#     pull in zero extra C deps. With no WITH_LIB* defined, libpsl uses its
#     built-in ASCII/punycode path (psl.c domain_to_punycode), which is
#     sufficient because the wrapper lower-cases and feeds ASCII candidates and
#     "fails secure" on anything it cannot classify.
#
# psl.c includes <config.h> (under HAVE_CONFIG_H), <libpsl.h> (the release
# tarball ships the generated include/libpsl.h), and "suffixes_dafsa.h"
# (under ENABLE_BUILTIN). We synthesize a minimal config.h here.

libpsl_build_rule = """
load("@rules_cc//cc:defs.bzl", "cc_library")

# Generate the compiled-in DAFSA from the bundled Public Suffix List, exactly
# as upstream's meson/automake build does:
#   python psl-make-dafsa --output-format=cxx+ <psl-file> suffixes_dafsa.h
genrule(
    name = "suffixes_dafsa_h",
    srcs = [
        "src/psl-make-dafsa",
        "list/public_suffix_list.dat",
    ],
    outs = ["src/suffixes_dafsa.h"],
    # PYTHONUTF8=1 so the PSL .dat (UTF-8, IDN names) reads on every platform;
    # genrules run through bash on all platforms.
    cmd = select({
        "@bazel_tools//src/conditions:windows": "PYTHONUTF8=1 python3 ./$(location src/psl-make-dafsa) --output-format=cxx+ ./$(location list/public_suffix_list.dat) $@",
        "//conditions:default": "python3 ./$(location src/psl-make-dafsa) --output-format=cxx+ ./$(location list/public_suffix_list.dat) $@",
    }),
)

# Minimal config.h. We deliberately enable ONLY the builtin PSL and the
# standard-header HAVE_* flags that are true on every toolchain we ship
# (glibc, musl, macOS, clang-cl). No WITH_LIB* (no IDNA runtime), no gettext.
genrule(
    name = "config_h",
    outs = ["src/config.h"],
    cmd = (
        "{ " +
        "echo '#ifndef LIBPSL_CONFIG_H'; " +
        "echo '#define LIBPSL_CONFIG_H'; " +
        "echo '#define ENABLE_BUILTIN 1'; " +
        "echo '#define PACKAGE_VERSION \\\"0.21.5\\\"'; " +
        "echo '#define HAVE_STDIO_H 1'; " +
        "echo '#define HAVE_STDLIB_H 1'; " +
        "echo '#define HAVE_STRING_H 1'; " +
        "echo '#define HAVE_STDINT_H 1'; " +
        "echo '#define HAVE_INTTYPES_H 1'; " +
        "echo '#define STDC_HEADERS 1'; " +
        "echo '#endif'; " +
        "} > $@"
    ),
)

cc_library(
    name = "libpsl",
    srcs = [
        "src/psl.c",
        "src/lookup_string_in_fixed_set.c",
        ":suffixes_dafsa_h",
        ":config_h",
    ],
    hdrs = [
        "include/libpsl.h",
        ":suffixes_dafsa_h",
        ":config_h",
    ],
    # `includes` (NOT raw -I copts) so the search paths cover BOTH the source
    # tree (src/psl.c, include/libpsl.h) AND the bazel-out genfiles tree where
    # the generated config.h + suffixes_dafsa.h land. Bazel's `includes`
    # attribute emits an -isystem (or /I) for each of {<pkg>/src, <pkg>/include}
    # under the exec-root AND under the genfiles root, so psl.c's
    # `#include <config.h>` and `#include "suffixes_dafsa.h"` resolve to the
    # genrule outputs while the checked-in sources resolve from source. Raw
    # `-Iexternal/libpsl/src` copts only cover the source variant — that is the
    # build break this fixes.
    includes = [
        "src",
        "include",
    ],
    # PSL_STATIC must also be visible to every CONSUMER of libpsl.h (e.g.
    # domain_registry.cc) so the API is declared without __declspec(dllimport);
    # otherwise lld-link looks for an import library and fails with
    # "undefined symbol: __declspec(dllimport) psl_builtin". `defines`
    # (unlike copts) propagate transitively to dependents. Windows-only.
    defines = select({
        "@bazel_tools//src/conditions:windows": ["PSL_STATIC"],
        "//conditions:default": [],
    }),
    # psl.c's isip() helper calls WSAStringToAddressW (Winsock) on Windows to
    # detect IP-literal hostnames; that symbol lives in ws2_32.lib. Static
    # libpsl.lib references it but does not pull it in, so any executable
    # linking @libpsl (the http_test, and downstream the nginx/IIS module)
    # fails with "undefined symbol __declspec(dllimport) WSAStringToAddressW".
    # linkopts propagate to dependents. Windows-only.
    linkopts = select({
        "@bazel_tools//src/conditions:windows": ["ws2_32.lib"],
        "//conditions:default": [],
    }),
    # -DHAVE_CONFIG_H so psl.c picks up our generated config.h.
    copts = select({
        "@bazel_tools//src/conditions:windows": [
            "/DHAVE_CONFIG_H",
            # libpsl is linked statically (libpsl.lib), so neutralize libpsl.h's
            # MSVC PSL_API __declspec(dllexport/dllimport) dance: with PSL_STATIC
            # defined, PSL_API collapses to empty and psl.c emits plain static
            # symbols (no dllexport). The matching consumer-side define lives in
            # `defines` below so domain_registry.cc imports them as static too.
            "/DPSL_STATIC",
        ],
        "//conditions:default": [
            "-DHAVE_CONFIG_H",
            # Upstream src is warning-clean under its own build but we compile
            # with the project's stricter flags; keep third-party warnings
            # non-fatal here (matches how other vendored C deps are treated).
            "-w",
        ],
    }),
    # The wrapper includes "external/libpsl/include/libpsl.h" (the same
    # external/<repo>/... convention drp used). That path resolves from the
    # exec root with no extra -I, but list the header in hdrs (above) so
    # Bazel's strict include checking accepts it.
    visibility = ["//visibility:public"],
)
"""
