# Repository rules for NGINX external dependency
#
# This file provides flexible configuration for NGINX source location:
#
# Option 1: new_local_repository (for local source checkout)
#   Use when you have NGINX source already checked out and configured.
#
# Option 2: http_archive (for downloading a specific version)
#   Downloads NGINX source, but requires manual ./configure step
#   or auto-generated config headers.
#
# Option 3: nginx_repository rule (auto-detects location)
#   Checks NGINX_PATH env var, then common locations.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Current stable NGINX version (as of 2026)
NGINX_VERSION = "1.26.3"
NGINX_SHA256 = ""  # Set this after downloading

def _nginx_repository_impl(repository_ctx):
    """Repository rule for NGINX that handles flexible source location.

    NGINX source is located in order of preference:
    1. NGINX_PATH environment variable
    2. Git submodule at third_party/nginx (relative to workspace)
    3. Platform-specific default: /usr/local/src/nginx (Linux/macOS)
    """
    # Check environment variable first
    nginx_path = repository_ctx.os.environ.get("NGINX_PATH", "")

    if not nginx_path:
        # Check for git submodule (relative to workspace root)
        workspace_root = str(repository_ctx.workspace_root)
        submodule_path = workspace_root + "/third_party/nginx"

        # Test if submodule path exists and has src directory
        result = repository_ctx.execute(["test", "-d", submodule_path + "/src"])
        if result.return_code == 0:
            nginx_path = submodule_path
        else:
            # Fall back to common location
            nginx_path = "/usr/local/src/nginx"

    # Symlink the source directories from nginx
    repository_ctx.symlink(nginx_path + "/src", "src")

    # Symlink objs directory if it exists (contains auto-generated headers)
    # This requires nginx to have been configured with ./configure
    objs_result = repository_ctx.execute(["test", "-d", nginx_path + "/objs"])
    if objs_result.return_code == 0:
        repository_ctx.symlink(nginx_path + "/objs", "objs")
    else:
        # Create a minimal objs directory with stub config headers
        # This allows compilation to proceed, but the module won't work
        # without a proper nginx configuration
        repository_ctx.file("objs/ngx_auto_config.h", _NGX_AUTO_CONFIG_STUB)
        repository_ctx.file("objs/ngx_auto_headers.h", _NGX_AUTO_HEADERS_STUB)

    # Write the BUILD file
    repository_ctx.file("BUILD.bazel", repository_ctx.read(
        repository_ctx.path(repository_ctx.attr.build_file)
    ))

nginx_repository = repository_rule(
    implementation = _nginx_repository_impl,
    attrs = {
        "build_file": attr.label(
            default = "@mod_pagespeed//bazel:nginx.BUILD",
            allow_single_file = True,
        ),
    },
    environ = ["NGINX_PATH"],
    local = True,
)

# Stub configuration headers for compilation without a configured nginx source
# These provide minimal definitions so code can compile, but the resulting
# module will need a properly configured nginx to actually run.

_NGX_AUTO_CONFIG_STUB = """
/* Stub ngx_auto_config.h - generated by bazel/nginx.bzl
 *
 * This is a minimal stub for compilation. For a working module,
 * use nginx source that has been configured with ./configure
 */

#ifndef NGX_AUTO_CONFIG_H_INCLUDED_
#define NGX_AUTO_CONFIG_H_INCLUDED_

/* Basic configuration */
#ifndef NGX_COMPILER
#define NGX_COMPILER "cc"
#endif

#ifndef NGX_PREFIX
#define NGX_PREFIX "/usr/local/nginx/"
#endif

#ifndef NGX_CONF_PREFIX
#define NGX_CONF_PREFIX "conf/"
#endif

#ifndef NGX_SBIN_PATH
#define NGX_SBIN_PATH "sbin/nginx"
#endif

#ifndef NGX_CONF_PATH
#define NGX_CONF_PATH "conf/nginx.conf"
#endif

#ifndef NGX_PID_PATH
#define NGX_PID_PATH "logs/nginx.pid"
#endif

#ifndef NGX_LOCK_PATH
#define NGX_LOCK_PATH "logs/nginx.lock"
#endif

#ifndef NGX_ERROR_LOG_PATH
#define NGX_ERROR_LOG_PATH "logs/error.log"
#endif

#ifndef NGX_HTTP_LOG_PATH
#define NGX_HTTP_LOG_PATH "logs/access.log"
#endif

#ifndef NGX_HTTP_CLIENT_TEMP_PATH
#define NGX_HTTP_CLIENT_TEMP_PATH "client_body_temp"
#endif

#ifndef NGX_HTTP_PROXY_TEMP_PATH
#define NGX_HTTP_PROXY_TEMP_PATH "proxy_temp"
#endif

#ifndef NGX_HTTP_FASTCGI_TEMP_PATH
#define NGX_HTTP_FASTCGI_TEMP_PATH "fastcgi_temp"
#endif

#ifndef NGX_HTTP_UWSGI_TEMP_PATH
#define NGX_HTTP_UWSGI_TEMP_PATH "uwsgi_temp"
#endif

#ifndef NGX_HTTP_SCGI_TEMP_PATH
#define NGX_HTTP_SCGI_TEMP_PATH "scgi_temp"
#endif

/* System types */
#define NGX_INT32_LEN (sizeof("-2147483648") - 1)
#define NGX_INT64_LEN (sizeof("-9223372036854775808") - 1)
#define NGX_PTR_SIZE 8
#define NGX_SIG_ATOMIC_T_SIZE 4
#define NGX_SIZE_T_SIZE 8
#define NGX_MAX_SIZE_T_VALUE 0xffffffffffffffffUL
#define NGX_OFF_T_LEN (sizeof("-9223372036854775808") - 1)
#define NGX_MAX_OFF_T_VALUE 0x7fffffffffffffffLL
#define NGX_TIME_T_SIZE 8
#define NGX_TIME_T_LEN (sizeof("-9223372036854775808") - 1)

/* Feature detection - assume modern Linux */
#define NGX_HAVE_EPOLL 1
#define NGX_HAVE_EVENTFD 1
#define NGX_HAVE_O_PATH 1
#define NGX_HAVE_SENDFILE 1
#define NGX_HAVE_SENDFILE64 1
#define NGX_HAVE_PR_SET_DUMPABLE 1
#define NGX_HAVE_SCHED_YIELD 1
#define NGX_HAVE_SCHED_SETAFFINITY 1
#define NGX_HAVE_REUSEPORT 1
#define NGX_HAVE_TRANSPARENT_PROXY 1
#define NGX_HAVE_IP_BIND_ADDRESS_NO_PORT 1
#define NGX_HAVE_IP_PKTINFO 1
#define NGX_HAVE_IPV6_RECVPKTINFO 1
#define NGX_HAVE_POSIX_FADVISE 1
#define NGX_HAVE_O_DIRECT 1
#define NGX_HAVE_ALIGNED_DIRECTIO 1
#define NGX_HAVE_STATFS 1
#define NGX_HAVE_STATVFS 1
#define NGX_HAVE_DLOPEN 1
#define NGX_HAVE_SO_SETFIB 0
#define NGX_HAVE_TCP_FASTOPEN 1
#define NGX_HAVE_UNIX_DOMAIN 1
#define NGX_HAVE_VARIADIC_MACROS 1
#define NGX_HAVE_GCC_VARIADIC_MACROS 1
#define NGX_HAVE_GCC_ATOMIC 1
#define NGX_HAVE_C99_VARIADIC_MACROS 1
#define NGX_HAVE_NONALIGNED 1
#define NGX_CPU_CACHE_LINE 64

/* Platform-specific types */
#define NGX_HAVE_LITTLE_ENDIAN 1
#define NGX_PTR_SIZE 8

/* PCRE */
#define NGX_PCRE 1
#define NGX_HAVE_PCRE_JIT 1

/* Zlib */
#define NGX_ZLIB 1

/* OpenSSL */
#define NGX_SSL 1
#define NGX_OPENSSL 1

/* HTTP/2 */
#define NGX_HTTP_V2 1

/* Headers */
#define NGX_HAVE_SYS_FILIO_H 0
#define NGX_HAVE_SYS_PARAM_H 1
#define NGX_HAVE_SYS_MOUNT_H 1
#define NGX_HAVE_SYS_STATVFS_H 1
#define NGX_HAVE_CRYPT_H 1
#define NGX_HAVE_LINUX_ADC_H 0
#define NGX_HAVE_SYS_PRCTL_H 1

/* Functions */
#define NGX_HAVE_ACCEPT4 1
#define NGX_HAVE_FILE_AIO 0
#define NGX_HAVE_POSIX_SEM 1
#define NGX_HAVE_MSGHDR_MSG_CONTROL 1
#define NGX_HAVE_FIONBIO 1
#define NGX_HAVE_GMTOFF 1
#define NGX_HAVE_D_TYPE 1
#define NGX_HAVE_SC_NPROCESSORS_ONLN 1
#define NGX_HAVE_LEVEL1_DCACHE_LINESIZE 1

/* Atomics */
#define NGX_HAVE_ATOMIC_OPS 1
#define NGX_HAVE_LIBATOMIC 0

/* Threads */
#define NGX_THREADS 1
#define NGX_MAX_THREADS 128

/* Modules - minimal set */
#define NGX_HTTP 1
#define NGX_MAIL 0
#define NGX_STREAM 0
#define NGX_GOOGLE_PERFTOOLS 0
#define NGX_COMPAT 1
#define NGX_DEBUG 0
#define NGX_STAT_STUB 1

#endif /* NGX_AUTO_CONFIG_H_INCLUDED_ */
"""

_NGX_AUTO_HEADERS_STUB = """
/* Stub ngx_auto_headers.h - generated by bazel/nginx.bzl
 *
 * This is a minimal stub for compilation. For a working module,
 * use nginx source that has been configured with ./configure
 */

#ifndef NGX_AUTO_HEADERS_H_INCLUDED_
#define NGX_AUTO_HEADERS_H_INCLUDED_

/* Standard headers */
#include <sys/types.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <string.h>
#include <signal.h>
#include <pwd.h>
#include <grp.h>
#include <dirent.h>
#include <glob.h>
#include <time.h>

/* Network headers */
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <sys/un.h>

/* File/IO headers */
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/uio.h>
#include <sys/mman.h>

/* Linux-specific */
#ifdef __linux__
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/sendfile.h>
#include <sys/prctl.h>
#include <sys/vfs.h>
#include <linux/capability.h>
#include <crypt.h>
#include <sys/syscall.h>
#include <sched.h>
#endif

/* POSIX threads */
#include <pthread.h>
#include <semaphore.h>

/* Dynamic loading */
#include <dlfcn.h>

/* Limits */
#include <limits.h>
#include <sys/param.h>

#endif /* NGX_AUTO_HEADERS_H_INCLUDED_ */
"""

def nginx_dependencies():
    """Register NGINX as an external dependency.

    Call this function from WORKSPACE after mod_pagespeed_dependencies().

    This sets up NGINX using the nginx_repository rule which:
    1. Checks NGINX_PATH environment variable
    2. Falls back to third_party/nginx submodule
    3. Falls back to /usr/local/src/nginx

    If nginx has not been configured (./configure), stub headers are generated
    that allow compilation but require a configured nginx for runtime.
    """
    nginx_repository(
        name = "nginx",
    )
