// Copyright (c) 2024-2026 We-Amp B.V.

#include "pagespeed/kernel/license_v2/license_verifier.h"

#include <chrono>
#include <cstring>

#include "ed25519.h"  // NOLINT(build/include_subdir)
#include "pagespeed/kernel/base/string.h"
#include "pagespeed/kernel/base/string_util.h"
#include "pagespeed/kernel/license_v2/license_token.h"

namespace net_instaweb {

// clang-format off
#ifdef PAGESPEED_TEST_LICENSE_KEY
// Test public key: Ed25519 derived from zero seed (for E2E testing only).
static const unsigned char kPublicKey[32] = {
    0x3b, 0x6a, 0x27, 0xbc, 0xce, 0xb6, 0xa4, 0x2d,
    0x62, 0xa3, 0xa8, 0xd0, 0x2a, 0x6f, 0x0d, 0x73,
    0x65, 0x32, 0x15, 0x77, 0x1d, 0xe2, 0x43, 0xa6,
    0x3a, 0xc0, 0x48, 0xa1, 0x8b, 0x59, 0xda, 0x29,
};
#else
// Production public key.
// Generated by tools/generate_keypair.py -- do NOT replace unless rotating keys.
static const unsigned char kPublicKey[32] = {
    0x98, 0xf6, 0x6e, 0x53, 0x7d, 0x36, 0xdb, 0xee,
    0xf6, 0xcc, 0x71, 0x85, 0x33, 0x38, 0x80, 0xf4,
    0x73, 0x7a, 0x10, 0x74, 0xb3, 0xcb, 0x18, 0x7c,
    0x0b, 0x37, 0x7e, 0xc5, 0xef, 0x53, 0x2b, 0xf6,
};
#endif

// Previous public key for dual-key rotation (accepts tokens signed with
// either key during rotation window).
static const unsigned char kPreviousPublicKey[32] = {
    0x95, 0xeb, 0x68, 0xe8, 0x9a, 0x38, 0x26, 0x79,
    0xc1, 0xb6, 0x6f, 0x2d, 0x7b, 0xc0, 0xa9, 0xe7,
    0x50, 0xa1, 0xb8, 0x2b, 0x58, 0xb2, 0xcc, 0x68,
    0xc5, 0x26, 0xa0, 0x9e, 0xe4, 0x9f, 0x17, 0x96,
};

// Key ID for the current signing key.
static const StringPiece kCurrentKeyId = "k1";
// clang-format on

// Returns true if all 32 bytes are zero (no previous key configured).
static bool IsZeroKey(const unsigned char key[32]) {
  unsigned char acc = 0;
  for (int i = 0; i < 32; ++i) acc |= key[i];
  return acc == 0;
}

// Maximum token size before base64url decoding (prevents memory abuse).
static constexpr size_t kMaxTokenLength = 2048;

LicenseResult VerifyLicenseTokenWithKey(StringPiece token,
                                        StringPiece public_key) {
  LicenseResult result;

  if (token.empty()) {
    result.error = "empty token";
    return result;
  }

  if (token.size() > kMaxTokenLength) {
    result.error = "token exceeds maximum length";
    return result;
  }

  if (public_key.size() != 32) {
    result.error = "invalid public key size";
    return result;
  }

  // Split token into signature + payload
  GoogleString signature;
  GoogleString json_payload;
  if (!SplitToken(token, &signature, &json_payload)) {
    result.error = "malformed token (base64url decode failed)";
    return result;
  }

  if (signature.size() != 64) {
    result.error = "malformed token (invalid signature length)";
    return result;
  }

  // Verify Ed25519 signature
  int ok = ed25519_verify(
      reinterpret_cast<const unsigned char*>(signature.data()),
      reinterpret_cast<const unsigned char*>(json_payload.data()),
      json_payload.size(),
      reinterpret_cast<const unsigned char*>(public_key.data()));

  if (!ok) {
    result.error = "invalid signature";
    return result;
  }

  // Parse the JSON payload
  if (!ParsePayload(json_payload, &result.payload)) {
    result.error = "valid signature but malformed payload JSON";
    return result;
  }

  // Verify issuer
  if (result.payload.iss != "modpagespeed.com") {
    result.error =
        "valid signature but unexpected issuer: " + result.payload.iss;
    return result;
  }

  result.valid = true;

  // Check expiry (v2 tokens only -- missing exp means no enforcement).
  if (result.payload.exp != 0) {
    result.expires_at = result.payload.exp;
    auto now = std::chrono::duration_cast<std::chrono::seconds>(
                   std::chrono::system_clock::now().time_since_epoch())
                   .count();
    result.expired = (now > result.payload.exp);
  }

  return result;
}

LicenseResult VerifyLicenseToken(StringPiece token) {
  LicenseResult result = VerifyLicenseTokenWithKey(
      token, StringPiece(reinterpret_cast<const char*>(kPublicKey), 32));

  if (result.valid) return result;

  // If primary key failed and we have a previous key, try it.
  // Skip fallback if the token's kid matches the current key ID (it was
  // signed with the current key, so fallback won't help).
  if (!IsZeroKey(kPreviousPublicKey)) {
    // We need to peek at kid to decide whether fallback is useful.
    // For non-signature errors (empty, too long, malformed), don't bother.
    if (result.error == "invalid signature") {
      LicenseResult fallback = VerifyLicenseTokenWithKey(
          token, StringPiece(
                     reinterpret_cast<const char*>(kPreviousPublicKey), 32));
      if (fallback.valid) {
        // Skip if kid matches current key -- shouldn't verify with old key.
        if (!kCurrentKeyId.empty() &&
            fallback.payload.kid == GoogleString(kCurrentKeyId)) {
          return result;  // Return original "invalid signature" result.
        }
        return fallback;
      }
    }
  }

  return result;
}

}  // namespace net_instaweb
