// GENERATED — DO NOT EDIT BY HAND.
// Vendored from ModPageSpeed 2.0 src/crypto/license_verifier.cc by tools/sync-crypto.sh.
// Canonical source: github.com/We-Amp/pagespeed-optimizer src/crypto/.
// Synced from commit 9621667d9af6cd397deff98aa3e2ea1e1677c812.
// To update: bump PINNED_MPS2_COMMIT in tools/sync-crypto.sh and re-run it.
// Drift guard: the crypto-drift CI check. See the design record.

// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2024-2026 We-Amp B.V.

#include "pagespeed/kernel/license_v2/license_verifier.h"

#include <chrono>
#include <cstring>
#include <string>
#include <string_view>

#include "ed25519.h"  // NOLINT(build/include_subdir)
#include "pagespeed/kernel/license_v2/license_token.h"

#ifndef PAGESPEED_LICENSE_NAMESPACE
#define PAGESPEED_LICENSE_NAMESPACE pagespeed
#endif

namespace PAGESPEED_LICENSE_NAMESPACE {

// clang-format off
#ifdef PAGESPEED_TEST_LICENSE_KEY
// Test public key: Ed25519 derived from zero seed (for E2E testing only).
static const unsigned char kPublicKey[32] = {
    0x3b, 0x6a, 0x27, 0xbc, 0xce, 0xb6, 0xa4, 0x2d,
    0x62, 0xa3, 0xa8, 0xd0, 0x2a, 0x6f, 0x0d, 0x73,
    0x65, 0x32, 0x15, 0x77, 0x1d, 0xe2, 0x43, 0xa6,
    0x3a, 0xc0, 0x48, 0xa1, 0x8b, 0x59, 0xda, 0x29,
};
#else
// Production public key.
// Generated by tools/generate_keypair.py — do NOT replace unless rotating keys.
static const unsigned char kPublicKey[32] = {
    0x98, 0xf6, 0x6e, 0x53, 0x7d, 0x36, 0xdb, 0xee,
    0xf6, 0xcc, 0x71, 0x85, 0x33, 0x38, 0x80, 0xf4,
    0x73, 0x7a, 0x10, 0x74, 0xb3, 0xcb, 0x18, 0x7c,
    0x0b, 0x37, 0x7e, 0xc5, 0xef, 0x53, 0x2b, 0xf6,
};
#endif

// Previous public key for dual-key rotation (accepts tokens signed with
// either key during rotation window).
static const unsigned char kPreviousPublicKey[32] = {
    0x95, 0xeb, 0x68, 0xe8, 0x9a, 0x38, 0x26, 0x79,
    0xc1, 0xb6, 0x6f, 0x2d, 0x7b, 0xc0, 0xa9, 0xe7,
    0x50, 0xa1, 0xb8, 0x2b, 0x58, 0xb2, 0xcc, 0x68,
    0xc5, 0x26, 0xa0, 0x9e, 0xe4, 0x9f, 0x17, 0x96,
};

// Key ID for the current signing key.
static constexpr std::string_view kCurrentKeyId = "k1";
// clang-format on

// Returns true if all 32 bytes are zero (no previous key configured).
static bool IsZeroKey(const unsigned char key[32]) {
  unsigned char acc = 0;
  for (int i = 0; i < 32; ++i) acc |= key[i];
  return acc == 0;
}

// Maximum token size before base64url decoding (prevents memory abuse).
static constexpr size_t kMaxTokenLength = 2048;

// Maximum allowed token lifetime: 2 years in seconds (365.25 * 2 * 86400).
static constexpr int64_t kMaxTokenLifetimeSec = 63072000;

LicenseResult VerifyLicenseTokenWithKey(std::string_view token,
                                        std::string_view public_key,
                                        int64_t now_sec) {
  LicenseResult result;

  if (token.empty()) {
    result.error = "empty token";
    return result;
  }

  if (token.size() > kMaxTokenLength) {
    result.error = "token exceeds maximum length";
    return result;
  }

  if (public_key.size() != 32) {
    result.error = "invalid public key size";
    return result;
  }

  // Split token into signature + payload
  std::string signature;
  std::string json_payload;
  if (!SplitToken(token, &signature, &json_payload)) {
    result.error = "malformed token (base64url decode failed)";
    return result;
  }

  if (signature.size() != 64) {
    result.error = "malformed token (invalid signature length)";
    return result;
  }

  // Verify Ed25519 signature
  int ok = ed25519_verify(
      reinterpret_cast<const unsigned char*>(signature.data()),
      reinterpret_cast<const unsigned char*>(json_payload.data()),
      json_payload.size(),
      reinterpret_cast<const unsigned char*>(public_key.data()));

  if (ok == 0) {
    result.error = "invalid signature";
    return result;
  }

  // Parse the JSON payload
  if (!ParsePayload(json_payload, &result.payload)) {
    result.error = "valid signature but malformed payload JSON";
    return result;
  }

  // Verify issuer
  if (result.payload.iss != "modpagespeed.com") {
    result.error =
        "valid signature but unexpected issuer: " + result.payload.iss;
    return result;
  }

  result.valid = true;

  // Validate iat/exp consistency for tokens with expiry.
  // Reject negative timestamps first to avoid signed overflow in subtraction.
  if (result.payload.exp != 0) {
    if (result.payload.iat < 0 || result.payload.exp < 0) {
      result.valid = false;
      result.error = "negative timestamp in token";
      return result;
    }
    if (result.payload.exp < result.payload.iat) {
      result.valid = false;
      result.error = "token expiry precedes issuance";
      return result;
    }
    if (result.payload.exp - result.payload.iat > kMaxTokenLifetimeSec) {
      result.valid = false;
      result.error = "token lifetime exceeds maximum";
      return result;
    }
  }

  // Check expiry (v2 tokens only — missing exp means no enforcement).
  if (result.payload.exp != 0) {
    result.expires_at = result.payload.exp;
    int64_t now = now_sec;
    if (now == 0) {
      now = std::chrono::duration_cast<std::chrono::seconds>(
                std::chrono::system_clock::now().time_since_epoch())
                .count();
    }
    result.expired = (now > result.payload.exp);
  }

  return result;
}

LicenseResult VerifyLicenseToken(std::string_view token, int64_t now_sec) {
  LicenseResult result = VerifyLicenseTokenWithKey(
      token, std::string_view(reinterpret_cast<const char*>(kPublicKey), 32),
      now_sec);

  if (result.valid) return result;

  // If primary key failed and we have a previous key, try it.
  // Skip fallback if the token's kid matches the current key ID (it was
  // signed with the current key, so fallback won't help).
  if (!IsZeroKey(kPreviousPublicKey)) {
    // We need to peek at kid to decide whether fallback is useful.
    // For non-signature errors (empty, too long, malformed), don't bother.
    if (result.error == "invalid signature") {
      LicenseResult fallback = VerifyLicenseTokenWithKey(
          token,
          std::string_view(reinterpret_cast<const char*>(kPreviousPublicKey),
                           32),
          now_sec);
      if (fallback.valid) {
        // Skip if kid matches current key — shouldn't verify with old key.
        if (!kCurrentKeyId.empty() &&
            fallback.payload.kid == std::string(kCurrentKeyId)) {
          result.error = "invalid token";
          return result;
        }
        return fallback;
      }
    }
  }

  // Normalize error to generic message to prevent info disclosure.
  // Specific errors are used internally for dual-key fallback above.
  if (!result.error.empty()) result.error = "invalid token";
  return result;
}

bool CheckProductAuthorization(const LicensePayload& payload,
                               std::string_view product_id) {
  if (payload.products.empty()) return false;
  for (const auto& p : payload.products) {
    if (p == product_id) return true;
  }
  return false;
}

bool CheckEntitlement(const LicensePayload& payload,
                      std::string_view entitlement) {
  if (payload.entitlements.empty()) return false;
  for (const auto& e : payload.entitlements) {
    if (e == entitlement) return true;
  }
  return false;
}

}  // namespace PAGESPEED_LICENSE_NAMESPACE
