#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 We-Amp B.V.
# Comprehensive dependency CVE scan — the design record (1.1 port).
#
# Generates SBOMs from DETERMINISTIC, COMMITTED inputs and scans them with grype:
#   - npm    : EVERY committed npm lockfile in the tree — the admin-console SPA
#              (the only SHIPPED JS surface), plus the dev/test JS toolchains
#              (browser tests, loadtest collector, js-minify corpus bundler).
#              Both lockfile dialects are handled: pnpm-lock.yaml and
#              package-lock.json. Scanning only the shipped surface was the
#              original scope and it was too narrow: a compromised dev/test
#              toolchain runs on CI runners with repo credentials, so it is a
#              real supply-chain surface even though it ships nothing. The
#              surface list below is COVERAGE-CHECKED against `git ls-files`
#              (see assert_npm_coverage) — adding a new lockfile without adding
#              it here is a loud failure, not a silent hole.
#   - images : (only with --images) the BUILT package-test images the release
#              pipeline produces — a real base OS (Ubuntu/Rocky + Apache/nginx)
#              with the actual shipped .deb / .rpm / ngx_pagespeed .so installed
#              on top (test/package-test/Dockerfile.*). Scanned from the local
#              docker cache. This is the OS / apt / dnf / built-module layer
#              grype matches reliably — the shipped C/C++ product surface, the
#              1.1 analogue of the 2.0 optimizer line's modpagespeed/worker + /nginx runtime images
#             . We deliberately do NOT scan the pagespeed1.1-dev build
#              image or the bare distro base images: a base/build image is false
#              confidence — it misses the package layer the product actually adds.
#
# Determinism: every source ecosystem is scanned from a COMMITTED lockfile,
# copied into an isolated temp dir so syft sees ONLY that file. We never
# `syft dir:.` a project tree (that pulls in whatever node_modules / obj / bin
# happen to be present; a .NET project dir was observed cataloging 744 npm
# pkgs) and we never generate a lockfile at scan time (a generated lockfile can
# resolve differently than what the product build pins — the exact drift this
# is meant to kill). Images are scanned by the build machine where they exist.
#
# DEV DEPENDENCIES ARE IN SCOPE (SYFT_JAVASCRIPT_INCLUDE_DEV_DEPENDENCIES below).
# syft's package-lock.json cataloger SKIPS `"dev": true` entries by default,
# which silently reduced two of these surfaces to a false 0/0/0/0: the
# js-minify corpus bundler catalogued 1 of its 163 locked packages and the
# browser tests 1 of 4, because those lockfiles are ~entirely devDependencies.
# A gate that reports "clean" over 162 unexamined packages is worse than no
# gate, so dev deps are included everywhere. (pnpm-lock.yaml is unaffected —
# syft's pnpm cataloger already reports the full `packages:` section.)
#
# NOT covered here (tracked in the design record / README):
#   - .NET (the aspnetcore middleware + WeAmpSite): its real surface is the
#     built .nupkg / publish output, not a dev-time `dotnet restore` — deferred
#     to a post-build scan, same as the 2.0 optimizer line.
#   - cargo: 1.1 ships NO Rust — there is no Cargo.toml / Cargo.lock anywhere in
#     the tree, so there is no cargo surface to scan (omitted, not stubbed).
#   - transitive vendored C/C++ Bazel deps (Envoy / libwebp / optipng / …):
#     covered by the SEPARATE cpp-cve-matcher work (Envoy-style per-dep
#     cpe+release_date+NVD model), NOT by this syft/grype scan.
#   - vendor/: NOT a scan surface. `vendor/` is .gitignored and GENERATED by
#     tools/vendor-deps.sh (Bazel repo-cache + a Cyclone checkout) — nothing in
#     it is committed, so it does not exist in a CI checkout and scanning it
#     would report findings that no reviewer can act on from this repo. A
#     `vendor/modpagespeed2/` tree may linger on a developer box as a leftover
#     of the pre-the design record `@modpagespeed2` Bazel git_repository; it is a stale
#     copy of a DIFFERENT repo's source, not a 1.1 dependency, and its CVEs
#     belong to pagespeed-optimizer. Do not add it here.
#
# TWO MODES:
#   REPORT-ONLY (default): prints a per-source severity histogram, writes SBOMs
#     + grype reports under $OUT_DIR, and ALWAYS exits 0. Used for the live-DB
#     sweep, which surfaces newly disclosed CVEs without ever reddening CI.
#   BLOCKING (--fail-on <sev>): same scan, exits NON-ZERO on gate hits. npm
#     gates UNCONDITIONALLY at <sev>+; images gate at <sev>+ when a fix is
#     available, and always at High/Critical. Restrict the scanned set with
#     --surfaces to keep still-report-only surfaces out of the gate.
#
# the design record RATCHET STATE: the npm surface is BLOCKING as of this change — all
# four committed lockfiles are clean at medium+ with NO VEX suppressions, so
# the gate is honest rather than a filter over a triaged backlog. Images remain
# report-only here (see dep-scan.yml). The curated medium+ gate in the CI workflow
# (security-gates) / release.yml is unchanged and still authoritative for the
# C/C++ SBOM.
#
# syft + grype must be on PATH at the pinned versions below.
set -uo pipefail

# See the DEV DEPENDENCIES note above — without this, package-lock.json
# surfaces that are all-devDependencies scan as empty and report a false clean.
export SYFT_JAVASCRIPT_INCLUDE_DEV_DEPENDENCIES=true

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${OUT_DIR:-${REPO_ROOT}/sbom/scan}"
GRYPE_SEVERITY="${GRYPE_SEVERITY:-medium}"   # reported threshold (NOT enforced)
SYFT_PIN="1.44.0"
GRYPE_PIN="0.112.0"
SCAN_IMAGES=0
SUMMARY_MD=""
WORK=""
VEX_ARGS=()
# --fail-on <sev>: blocking mode. Empty = report-only (default, always exit 0).
FAIL_ON=""
# --surfaces <csv>: restrict the scanned set (e.g. "npm"). Empty = all.
SURFACES=""
GATE_HITS=0   # total over-threshold findings across all scanned surfaces

# bash 3.2 (macOS) safe: no associative arrays, no ${var,,} — lower via tr.
lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# sev_rank <sev> -> numeric rank (low<medium<high<critical); unknown -> 0.
sev_rank() {
  case "$(lc "$1")" in
    low) echo 1 ;; medium) echo 2 ;; high) echo 3 ;; critical) echo 4 ;;
    *) echo 0 ;;
  esac
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --images) SCAN_IMAGES=1 ;;
    --fail-on) shift; FAIL_ON="${1:-}" ;;
    --fail-on=*) FAIL_ON="${1#*=}" ;;
    --surfaces) shift; SURFACES="${1:-}" ;;
    --surfaces=*) SURFACES="${1#*=}" ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

if [ -n "$FAIL_ON" ]; then
  case "$(lc "$FAIL_ON")" in
    low|medium|high|critical) ;;
    *) echo "::error::--fail-on must be one of low|medium|high|critical (got '$FAIL_ON')" >&2; exit 2 ;;
  esac
fi

# want_surface <kind> — is this surface in the requested --surfaces set?
# Empty SURFACES means "all". Matches on the scan kind (npm/image).
want_surface() {
  [ -z "$SURFACES" ] && return 0
  case ",$(lc "$SURFACES")," in
    *",$(lc "$1"),"*) return 0 ;;
    *) return 1 ;;
  esac
}

# Built package-test images (local docker tags). These bake the actual shipped
# .deb / .rpm / nginx .so into a production-representative base OS, so they carry
# the real product C/C++ + apt/dnf surface (test/package-test/Dockerfile.*):
#   - mps-smoke-nginx                : release.yml builds this tag directly
#                                      (Dockerfile.ubuntu-nginx + module .so).
#   - package-test-test-ubuntu-apache: default docker-compose tag for
#                                      Dockerfile.ubuntu-apache (.deb installed).
#   - package-test-test-rocky-apache : default docker-compose tag for
#                                      Dockerfile.rocky-apache (.rpm installed).
# Absent images skip cleanly with an explicit "not built" row — we never fall
# back to scanning a base/build image as a proxy.
PRODUCT_IMAGES="
mps-smoke-nginx:latest
package-test-test-ubuntu-apache:latest
package-test-test-rocky-apache:latest
"

# Every COMMITTED npm lockfile, as "<surface-name> <repo-relative-path>".
# assert_npm_coverage cross-checks this list against `git ls-files`, so this is
# the single place to register a new JS surface.
#   admin-console          - the shipped admin SPA (pagespeed/system/console)
#   browser-tests          - Playwright/browser harness (test/browser)
#   loadtest-collect       - load-test result collector (devel/loadtest_collect)
#   minify-corpus-fixtures - pinned bundler toolchain used to grow the
#                            js-minify corpus (tools/js-minify-corpus)
NPM_LOCKFILES="
admin-console pagespeed/system/console/pnpm-lock.yaml
browser-tests test/browser/package-lock.json
loadtest-collect devel/loadtest_collect/package-lock.json
minify-corpus-fixtures tools/js-minify-corpus/bundle-fixtures/package-lock.json
"

note() { printf '\033[36m[dep-scan]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[33m[dep-scan] WARN:\033[0m %s\n' "$*" >&2; }

cleanup() { [ -n "$WORK" ] && rm -rf "$WORK"; }
trap cleanup EXIT

require_tool() {
  local tool="$1" pin="$2" have
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "::error::$tool not found on PATH (pin $pin)"; exit 3
  fi
  have="$("$tool" version 2>/dev/null | awk '/^Version:/{print $2; exit}')"
  if [ -n "$have" ] && [ "$have" != "$pin" ]; then
    if [ -n "$FAIL_ON" ]; then
      # Blocking runs gate on grype JSON fields (fix.state enum) and on syft
      # cataloger behaviour (the dev-dependency switch); an unpinned tool could
      # drift either and silently fail the gate OPEN. Hard stop.
      echo "::error::$tool $have != pinned $pin — refusing to run a BLOCKING scan on an unpinned tool" >&2
      exit 3
    fi
    warn "$tool $have != pinned $pin (results may differ)"
  fi
}

# assert_npm_coverage — every committed npm lockfile must be registered in
# NPM_LOCKFILES. This is the guard for the failure this scan was widened to
# fix: the surface list drifted behind the tree and three lockfiles went
# unscanned for the entire report-only life of the gate, while the summary
# table looked complete. A new lockfile is a loud row (and a gate hit in
# blocking mode), never a silent hole.
assert_npm_coverage() {
  command -v git >/dev/null 2>&1 || { warn "git unavailable; skipping npm lockfile coverage check"; return; }
  local tracked registered missing=""
  tracked="$(git -C "$REPO_ROOT" ls-files -- '*package-lock.json' '*pnpm-lock.yaml' '*yarn.lock' 2>/dev/null)"
  [ -n "$tracked" ] || { warn "git ls-files returned no lockfiles; skipping coverage check"; return; }
  registered="$(printf '%s\n' "$NPM_LOCKFILES" | awk 'NF{print $2}')"
  local f
  for f in $tracked; do
    # Herestring, not a pipe: `grep -q` exits on the first match and a
    # `printf | grep -q` pipeline then fails under pipefail whenever printf
    # loses the race to write ("printf: write error: Broken pipe"), which
    # reported a REGISTERED lockfile as unscanned and failed the gate.
    grep -qxF -- "$f" <<<"$registered" || missing="${missing}${f} "
  done
  [ -z "$missing" ] && { note "npm lockfile coverage: all $(printf '%s\n' "$tracked" | grep -c .) committed lockfile(s) registered"; return; }
  warn "UNSCANNED committed npm lockfile(s) — add them to NPM_LOCKFILES: ${missing}"
  emit_row "npm-coverage" npm "**unscanned**" "$(printf '%s' "$missing" | tr ' ' '\n' | grep -c .) lockfile(s) missing"
  [ -n "$FAIL_ON" ] && GATE_HITS=$((GATE_HITS + 1))
  return 0
}

emit_row() { printf '| %s | %s | %s | %s |\n' "$1" "$2" "$3" "$4" >>"$SUMMARY_MD"; }

# run_scan <kind> <name> <syft-source>   (source carries its prefix: dir:/docker:)
#   syft -> SBOM, grype (+VEX) -> report, appends a severity row. Distinguishes
#   a FAILED scan (syft/grype error or non-JSON report) from a genuinely clean one.
run_scan() {
  local kind="$1" name="$2" src="$3"
  local sbom="${OUT_DIR}/${name}.spdx.json" rpt="${OUT_DIR}/${name}.grype.json"
  if ! syft "${src}" -o "spdx-json=${sbom}" -q 2>"${OUT_DIR}/${name}.syft.err"; then
    warn "syft FAILED for ${name} (${src}) — see ${name}.syft.err"
    if [ -n "$FAIL_ON" ]; then GATE_HITS=$((GATE_HITS + 1)); fi
    emit_row "$name" "$kind" "scan-failed" "**scan failed**"; return
  fi
  local pkgs; pkgs="$(jq '.packages | length - 1' "$sbom" 2>/dev/null || echo '?')"
  if ! grype "sbom:${sbom}" ${VEX_ARGS[@]+"${VEX_ARGS[@]}"} -o json >"$rpt" 2>"${OUT_DIR}/${name}.grype.err"; then
    warn "grype FAILED for ${name} — see ${name}.grype.err"
    if [ -n "$FAIL_ON" ]; then GATE_HITS=$((GATE_HITS + 1)); fi
    emit_row "$name" "$kind" "$pkgs" "**scan failed**"; return
  fi
  # A valid grype report has a .matches array; anything else = broken scan, not "clean".
  if ! jq -e 'has("matches")' "$rpt" >/dev/null 2>&1; then
    warn "grype produced no .matches for ${name} — treating as scan failure"
    if [ -n "$FAIL_ON" ]; then GATE_HITS=$((GATE_HITS + 1)); fi
    emit_row "$name" "$kind" "$pkgs" "**scan failed**"; return
  fi
  # An empty catalog is a scan failure, not a clean surface: every registered
  # lockfile pins at least one package, so 0 packages means the cataloger
  # skipped the file (wrong dialect, unsupported lockfileVersion, or the dev
  # -dependency switch regressing) and the 0/0/0/0 below would be a lie.
  if [ "$kind" != "image" ] && [ "$pkgs" = "0" ]; then
    warn "${name}: syft catalogued 0 packages — treating as scan failure, not clean"
    if [ -n "$FAIL_ON" ]; then GATE_HITS=$((GATE_HITS + 1)); fi
    emit_row "$name" "$kind" "0" "**scan failed (empty catalog)**"; return
  fi
  local c h m l
  c="$(jq '[.matches[]|select(.vulnerability.severity=="Critical")]|length' "$rpt")"
  h="$(jq '[.matches[]|select(.vulnerability.severity=="High")]|length'     "$rpt")"
  m="$(jq '[.matches[]|select(.vulnerability.severity=="Medium")]|length'   "$rpt")"
  l="$(jq '[.matches[]|select(.vulnerability.severity=="Low")]|length'      "$rpt")"
  note "${name} (${kind}): ${pkgs} pkgs — ${c}C/${h}H/${m}M/${l}L"

  # Blocking mode. Two gate shapes by surface kind (mirrors the 2.0 optimizer line's dep-scan.sh):
  #
  #   npm   : UNCONDITIONAL — any finding at/above --fail-on gates. A registry
  #     advisory with no published fix still forces a dep replacement or a
  #     justified VEX entry; there is no "unfixable tail" excuse for a lockfile
  #     the repo controls outright.
  #
  #   image : the MEDIUM band gates only when ACTIONABLE (fix.state == "fixed"),
  #     because a shipped image's OS population carries a permanent
  #     wont-fix/not-fixed medium tail that no rebuild can clear, and papering
  #     over it with unprovable not_affected VEX claims would be dishonest.
  #     High/Critical always gate, fixable or not.
  #
  # The FULL population (gating or not) is always reported above and lands in
  # the daily tracking issue.
  if [ -n "$FAIL_ON" ]; then
    local want img over unfixable
    want="$(sev_rank "$FAIL_ON")"
    if [ "$kind" = "image" ]; then img=true; else img=false; fi
    local gate_jq='def rank: {"low":1,"medium":2,"high":3,"critical":4}[.vulnerability.severity|ascii_downcase] // 0;
              .matches[]|select( (rank >= $w)
                and ( ($img|not) or .vulnerability.fix.state == "fixed" or rank >= 3 ) )'
    over="$(jq --argjson w "$want" --argjson img "$img" "[${gate_jq}]|length" "$rpt")"
    unfixable="$(jq --argjson w "$want" --argjson img "$img" '
              def rank: {"low":1,"medium":2,"high":3,"critical":4}[.vulnerability.severity|ascii_downcase] // 0;
              [.matches[]|select( $img and (rank >= $w) and rank < 3
                and .vulnerability.fix.state != "fixed" )]|length' "$rpt")"
    [ "$unfixable" -gt 0 ] && \
      warn "${name}: ${unfixable} medium-band finding(s) with NO fix available — reported + issue-tracked, not gating"
    if [ "$over" -gt 0 ]; then
      GATE_HITS=$((GATE_HITS + over))
      warn "${name}: ${over} finding(s) >= ${FAIL_ON} — BLOCKING:"
      jq -r --argjson w "$want" --argjson img "$img" "${gate_jq}
              | \"    \(.artifact.name)@\(.artifact.version) \(.vulnerability.id) [\(.vulnerability.severity)] fix=\(.vulnerability.fix.versions|join(\",\")//\"none\")\"" "$rpt" >&2
      emit_row "$name" "$kind" "$pkgs" "${c} / ${h} / ${m} / ${l} ❌"
    else
      emit_row "$name" "$kind" "$pkgs" "${c} / ${h} / ${m} / ${l} ✅"
    fi
  else
    emit_row "$name" "$kind" "$pkgs" "${c} / ${h} / ${m} / ${l}"
  fi
}

# scan_lockfiles <kind> <name> <lockfile> [lockfile...]
#   Copies the given COMMITTED lockfiles into an isolated temp dir (so syft sees
#   ONLY them) and scans. A missing lockfile is a loud row, not a silent skip.
scan_lockfiles() {
  local kind="$1" name="$2"; shift 2
  local d="${WORK}/${name}" f any=0
  mkdir -p "$d"
  for f in "$@"; do
    if [ -f "$f" ]; then cp "$f" "$d/"; any=1; else warn "missing committed lockfile: $f"; fi
  done
  if [ "$any" != "1" ]; then
    warn "no lockfile for ${name}; NOT scanned"
    # In blocking mode a vanished lockfile must fail the gate, not pass it: a
    # registered surface that silently stops being scanned is the exact hole
    # this widening closed.
    if [ -n "$FAIL_ON" ]; then GATE_HITS=$((GATE_HITS + 1)); fi
    emit_row "$name" "$kind" "**no lockfile**" "—"; return
  fi
  run_scan "$kind" "$name" "dir:${d}"
}

main() {
  require_tool syft "$SYFT_PIN"
  require_tool grype "$GRYPE_PIN"
  command -v jq >/dev/null 2>&1 || { echo "::error::jq required"; exit 3; }
  [ -n "$OUT_DIR" ] || { echo "::error::OUT_DIR empty"; exit 3; }
  rm -rf "$OUT_DIR"; mkdir -p "$OUT_DIR"
  WORK="$(mktemp -d)"
  SUMMARY_MD="${OUT_DIR}/SUMMARY.md"

  # Apply the same VEX suppressions the blocking gate uses, so the report
  # reflects post-triage reality and the ratchet ("clean at medium+") is real.
  # (The 1.1 gate expects a single sbom/pagespeed-1.1.vex.json; the glob handles
  # zero, one, or several without tripping `set -u` if none exist yet.)
  local vexfile
  for vexfile in "${REPO_ROOT}"/sbom/*.vex.json; do
    [ -f "$vexfile" ] && VEX_ARGS+=(--vex "$vexfile") && note "applying VEX: $(basename "$vexfile")"
  done

  local mode_line scope_line
  if [ -n "$FAIL_ON" ]; then
    mode_line="enforced \`${FAIL_ON}+\` · **BLOCKING** (npm: any over-threshold finding; images: fixable at threshold, High/Critical always)"
  else
    mode_line="reported \`${GRYPE_SEVERITY}+\` · **report-only** (always exits 0)"
  fi
  scope_line="${SURFACES:-all surfaces}"
  {
    echo "## Dependency scan"
    echo ""
    echo "syft \`${SYFT_PIN}\` · grype \`${GRYPE_PIN}\` · scope \`${scope_line}\` · ${mode_line}"
    echo ""
    echo "| Source | Ecosystem | Pkgs | Crit / High / Med / Low |"
    echo "|---|---|--:|---|"
  } >"$SUMMARY_MD"

  # --- npm (every committed lockfile; see NPM_LOCKFILES) ---
  if want_surface npm; then
    assert_npm_coverage
    local nname npath
    while read -r nname npath; do
      [ -n "$nname" ] || continue
      scan_lockfiles npm "$nname" "${REPO_ROOT}/${npath}"
    done <<EOF
$(printf '%s\n' "$NPM_LOCKFILES" | awk 'NF')
EOF
  fi

  # --- built package-test images (local docker cache; the real shipped surface) ---
  # KNOWN BLIND SPOT: these images only exist in the local docker cache AFTER a
  # release build, so on the daily scheduled run they are typically all
  # "**not built**" and this surface covers nothing. The rows are honest about
  # it (never a 0/0/0/0), but the schedule does not itself produce the images,
  # so "no image findings" here means "no images", not "no CVEs". Making the
  # scheduled run build or pull them is out of scope for this change.
  if [ "$SCAN_IMAGES" = "1" ] && want_surface image; then
    if command -v docker >/dev/null 2>&1; then
      local img slug
      for img in $PRODUCT_IMAGES; do
        if docker image inspect "$img" >/dev/null 2>&1; then
          slug="$(printf '%s' "$img" | tr '/:' '--')"
          run_scan image "$slug" "docker:${img}"
        else
          warn "image not in local cache (build it first): ${img}"
          emit_row "$(printf '%s' "$img" | tr '/:' '--')" image "**not built**" "—"
        fi
      done
    else
      warn "docker not present; skipping image scans"
    fi
  else
    note "image scan skipped (pass --images; runs on the build machine where images exist)"
  fi

  {
    echo ""
    if [ -n "$FAIL_ON" ]; then
      echo "_Blocking gate. npm: ANY finding at or above \`${FAIL_ON}\` fails."
      echo "Images: findings at or above \`${FAIL_ON}\` fail when a fix is available; High/Critical always fail."
      echo "The out is a bump/rebuild, or an evidence-backed \`sbom/*.vex.json\` entry — never a filter._"
    else
      echo "_Report-only. Triage findings into \`sbom/*.vex.json\` (applied when present);"
      echo "flip a surface to blocking once clean. .NET (built .nupkg) + transitive vendored C/C++"
      echo "(separate cpp-cve-matcher) are out of scope here — see tools/sbom/README.md._"
    fi
  } >>"$SUMMARY_MD"
  note "summary -> ${SUMMARY_MD}"
  cat "$SUMMARY_MD" >&2

  if [ -n "$FAIL_ON" ] && [ "$GATE_HITS" -gt 0 ]; then
    echo "::error::dep-scan BLOCKING: ${GATE_HITS} gating finding(s) >= ${FAIL_ON} on scope '${scope_line}'. Bump/rebuild to pick up the fix, or add a justified sbom/*.vex.json entry." >&2
    exit 1
  fi
  exit 0
}

main "$@"
