#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 We-Amp B.V.

"""Slow, flushing HTTP origin for the pytest system-test lanes.

Stands in for the PHP pages the bash suite used to exercise flush handling
(install/mod_pagespeed_test/{slow_flushing_html_response,php_withflush,
php_withoutflush,php_gzip}.php and image_rewrite_with_flush/*.php). The
Apache lane proxies /mod_pagespeed_test/flush_origin/ here with
"ProxyPass ... flushpackets=on", so every chunk written and flushed below
reaches mod_pagespeed as a FLUSH bucket -- the event mod_php's flush()
produced.

Routes (the path after /mod_pagespeed_test/flush_origin/):
  slow_flushing_html_response  <html><head></head><body>, then five
                               "<p>foo</p><div>bar:N</div>" chunks, each
                               followed by a pause (1 s; ?delay=S overrides),
                               then </body></html>
  withoutflush                 one Content-Length response,
                               X-My-PHP-Header: without_flush
  withflush                    X-My-PHP-Header: with_flush; the page head is
                               flushed as its own chunk before the text
  image_rewrite_with_flush     flush inside <li data-thumb="a.jpg">
  a.jpg                        <image-dir>/a.jpg
  gzip.css                     pre-gzipped CSS (Content-Encoding: gzip)
  content_type_present/        200 text/plain "This file should be proxied"
  content_type_absent/         200 without a Content-Type header (proxying.sh)
  health                       200 "ok" (setup_apache_test.sh readiness probe)

Usage: flush_origin.py --port 8093 --image-dir <dir holding a.jpg>
"""

import argparse
import gzip
import http.server
import os
import time
from email.utils import formatdate
from typing import List, Tuple
from urllib.parse import parse_qs, urlsplit

# Pause after each flushed chunk of the with-flush pages: long enough that
# the proxy's non-blocking read of the backend comes up empty and the proxy
# flushes what it has, as it would for a PHP page blocked after flush().
FLUSH_PAUSE_S = 0.2

XHTML_HEAD = (
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" '
    '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n'
    '<html xmlns="http://www.w3.org/1999/xhtml" lang="en">\n'
    "<head>\n"
    "</head>\n"
    "<body>\n"
)


class FlushOriginHandler(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    server_version = "FlushOrigin/1.0"

    def log_message(self, fmt, *args):  # keep the lane log readable
        pass

    # -- response helpers ---------------------------------------------------

    def _start(self, content_type: str, extra: List[Tuple[str, str]], length=None):
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        for name, value in extra:
            self.send_header(name, value)
        if length is None:
            self.send_header("Transfer-Encoding", "chunked")
        else:
            self.send_header("Content-Length", str(length))
        self.end_headers()

    def _chunk(self, data: bytes, pause: float = 0.0):
        self.wfile.write(b"%x\r\n%s\r\n" % (len(data), data))
        self.wfile.flush()
        if pause:
            time.sleep(pause)

    def _end_chunks(self):
        self.wfile.write(b"0\r\n\r\n")
        self.wfile.flush()

    def _whole(self, content_type: str, body: bytes, extra: List[Tuple[str, str]]):
        self._start(content_type, extra, length=len(body))
        self.wfile.write(body)
        self.wfile.flush()

    # -- routes ---------------------------------------------------------------

    def do_GET(self):
        parts = urlsplit(self.path)
        route = parts.path.lstrip("/")
        query = parse_qs(parts.query)
        if route == "slow_flushing_html_response":
            delay = float(query.get("delay", ["1"])[0])
            self._start("text/html", [])
            self._chunk(b"<html><head></head><body>\n")
            for i in range(1, 6):
                self._chunk(b"<p>foo</p><div>bar:%d</div>\n" % i, pause=delay)
            self._chunk(b"</body></html>\n")
            self._end_chunks()
        elif route == "withoutflush":
            body = (
                XHTML_HEAD
                + "Content generated by PHP without a call to flush()!\n</body>\n</html>\n"
            ).encode()
            self._whole("text/html; charset=UTF-8", body,
                        [("X-My-PHP-Header", "without_flush")])
        elif route == "withflush":
            self._start("text/html; charset=UTF-8", [("X-My-PHP-Header", "with_flush")])
            self._chunk(XHTML_HEAD.encode(), pause=FLUSH_PAUSE_S)
            self._chunk(b"Content generated by PHP with a call to flush()!\n</body>\n</html>\n")
            self._end_chunks()
        elif route == "image_rewrite_with_flush":
            self._start("text/html; charset=UTF-8", [("X-My-PHP-Header", "with_flush")])
            self._chunk(
                (
                    XHTML_HEAD.replace(
                        "<head>\n</head>\n",
                        "<head>\n  <title>Title of the document </title>\n</head>\n",
                    )
                    + '<ul>\n  <li data-thumb="a.jpg">\n    '
                ).encode(),
                pause=FLUSH_PAUSE_S,
            )
            self._chunk(
                b"Content generated by PHP with a call to flush()!\n"
                b'    <img src="a.jpg"/>\n   </li>\n</ul>\n</body>\n</html>\n'
            )
            self._end_chunks()
        elif route == "a.jpg":
            with open(os.path.join(self.server.image_dir, "a.jpg"), "rb") as f:
                body = f.read()
            self._whole("image/jpeg", body, [("Cache-Control", "max-age=600")])
        elif route == "gzip.css":
            unique = "%x" % time.time_ns()
            pad = (unique * (10000 // len(unique) + 1))[:10000]
            css = (
                ".peachpuff {background-color: peachpuff;}\n."
                + pad
                + " {background-color: antiquewhite;}\n"
            ).encode()
            self._whole(
                "text/css",
                gzip.compress(css, compresslevel=2, mtime=0),
                [
                    ("Cache-Control", "max-age=86400"),
                    ("Expires", formatdate(time.time() + 86400, usegmt=True)),
                    ("Content-Encoding", "gzip"),
                ],
            )
        elif route == "content_type_present/":
            self._whole("text/plain", b"This file should be proxied\n", [])
        elif route == "content_type_absent/":
            body = b"This file should not be proxied\n"
            self.send_response(200)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            self.wfile.flush()
        elif route == "health":
            self._whole("text/plain", b"ok", [])
        else:
            self.send_error(404)


def make_server(port: int, image_dir: str, host: str = "127.0.0.1"):
    """A threading origin on host:port (0 = ephemeral), serving image_dir/a.jpg."""
    server = http.server.ThreadingHTTPServer((host, port), FlushOriginHandler)
    server.daemon_threads = True
    server.image_dir = image_dir
    return server


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--port", type=int, default=8093)
    parser.add_argument("--image-dir", required=True)
    args = parser.parse_args()
    make_server(args.port, args.image_dir).serve_forever()


if __name__ == "__main__":
    main()
