#!/bin/sh

# Based on postinst from Chromium and Google Talk.

@@include@@../common/apt.include

MODPAGESPEED_ENABLE_UPDATES=@@MODPAGESPEED_ENABLE_UPDATES@@

case "$1" in
    configure)
        if [ -n "${MODPAGESPEED_ENABLE_UPDATES}" -a ! -e "$DEFAULTS_FILE" ]; then
            echo 'repo_add_once="true"' > "$DEFAULTS_FILE"
            echo 'repo_reenable_on_distupgrade="true"' >> "$DEFAULTS_FILE"
        fi

        # Run the cron job immediately to perform repository
        # configuration.
        nohup sh /etc/cron.daily/@@PACKAGE@@ > /dev/null 2>&1 &

        test ! -e /etc/apache2/mods-enabled/pagespeed.load && \
            a2enmod pagespeed

        # Enable pagespeed_libraries.conf if it was installed.
        # Bazel builds may not include this file.
        if [ -f /etc/apache2/conf-available/pagespeed_libraries.conf ]; then
          if hash a2enconf 2> /dev/null; then
            a2enconf pagespeed_libraries
          elif [ -d /etc/apache2/conf.d/ ]; then
            if [ -e /etc/apache2/conf.d/pagespeed_libraries.conf ]; then
              echo "Not symlinking on top of existing pagespeed_libraries.conf"
            else
              ln -s ../conf-available/pagespeed_libraries.conf \
                    /etc/apache2/conf.d/
            fi
          fi
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
