#!/bin/bash
#
# Sets up Envoy with PageSpeed filter for running Python system tests.
#
# Usage (inside Docker container):
#   ./test/system/setup_envoy_test.sh [start|stop|status]
#
# After starting, run Python tests with:
#   PAGESPEED_SERVER_TYPE=envoy PAGESPEED_PORT=8080 \
#       python3 -m pytest test/system/automatic/ -v
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration
ENVOY_BINARY="$PROJECT_ROOT/bazel-bin/pagespeed/envoy/envoy_pagespeed"
ENVOY_CONFIG_DIR="${ENVOY_CONFIG_DIR:-/tmp/envoy_pagespeed_test}"
ENVOY_PID_FILE="$ENVOY_CONFIG_DIR/envoy.pid"
ENVOY_LOG_FILE="$ENVOY_CONFIG_DIR/envoy.log"
ENVOY_CONFIG_FILE="$ENVOY_CONFIG_DIR/envoy.yaml"
CACHE_DIR="$ENVOY_CONFIG_DIR/cache"
# Default PageSpeed cache directory (must match envoy_rewrite_driver_factory.cc)
PAGESPEED_CACHE_DIR="/tmp/envoy_pagespeed_cache"

# Ports
ENVOY_PORT="${ENVOY_PORT:-8080}"
ENVOY_HTTPS_PORT="${ENVOY_HTTPS_PORT:-8443}"
ENVOY_ADMIN_PORT="${ENVOY_ADMIN_PORT:-9901}"

# TLS configuration
TLS_CERT_FILE="$ENVOY_CONFIG_DIR/certs/server.crt"
TLS_KEY_FILE="$ENVOY_CONFIG_DIR/certs/server.key"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_binary() {
    if [ ! -f "$ENVOY_BINARY" ]; then
        log_error "Envoy binary not found at $ENVOY_BINARY"
        log_info "Build it first with:"
        log_info "  bazel build --config=gcc --jobs=2 //pagespeed/envoy:envoy_pagespeed"
        log_info ""
        log_warn "Note: Building Envoy requires significant memory (16GB+ recommended)"
        return 1
    fi
    return 0
}

generate_tls_certs() {
    log_info "Generating self-signed TLS certificates..."

    local CERT_DIR="$ENVOY_CONFIG_DIR/certs"
    mkdir -p "$CERT_DIR"

    # Check if certs already exist and are valid
    if [ -f "$TLS_CERT_FILE" ] && [ -f "$TLS_KEY_FILE" ]; then
        # Check if cert is still valid (not expired)
        if openssl x509 -checkend 86400 -noout -in "$TLS_CERT_FILE" 2>/dev/null; then
            log_info "TLS certificates already exist and are valid"
            return 0
        fi
        log_info "Existing certificates expired, regenerating..."
    fi

    # Generate self-signed certificate valid for 365 days
    # Subject includes localhost and common test hostnames
    openssl req -x509 -newkey rsa:2048 \
        -keyout "$TLS_KEY_FILE" \
        -out "$TLS_CERT_FILE" \
        -days 365 \
        -nodes \
        -subj "/C=US/ST=Test/L=Test/O=PageSpeed/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:127.0.0.1,IP:127.0.0.1" \
        2>/dev/null

    if [ $? -eq 0 ]; then
        log_info "TLS certificates generated:"
        log_info "  Certificate: $TLS_CERT_FILE"
        log_info "  Private key: $TLS_KEY_FILE"
    else
        log_error "Failed to generate TLS certificates"
        return 1
    fi
}

setup_directories() {
    log_info "Setting up directories..."
    mkdir -p "$ENVOY_CONFIG_DIR"
    mkdir -p "$CACHE_DIR"
    mkdir -p "$ENVOY_CONFIG_DIR/logs"
    # Create PageSpeed cache directory for CycloneCache
    mkdir -p "$PAGESPEED_CACHE_DIR"
}

setup_test_content() {
    log_info "Setting up test content..."

    # Create document root
    local DOC_ROOT="$ENVOY_CONFIG_DIR/www"
    mkdir -p "$DOC_ROOT"

    # Copy test content
    if [ -d "$PROJECT_ROOT/install/mod_pagespeed_example" ]; then
        rm -rf "$DOC_ROOT/mod_pagespeed_example"
        cp -r "$PROJECT_ROOT/install/mod_pagespeed_example" "$DOC_ROOT/"
    else
        log_warn "mod_pagespeed_example not found in install/"
    fi

    if [ -d "$PROJECT_ROOT/install/mod_pagespeed_test" ]; then
        rm -rf "$DOC_ROOT/mod_pagespeed_test"
        cp -r "$PROJECT_ROOT/install/mod_pagespeed_test" "$DOC_ROOT/"
    else
        log_warn "mod_pagespeed_test not found in install/"
    fi

    if [ -d "$PROJECT_ROOT/install/do_not_modify" ]; then
        rm -rf "$DOC_ROOT/do_not_modify"
        cp -r "$PROJECT_ROOT/install/do_not_modify" "$DOC_ROOT/"
    fi

    # Create a simple index.html if nothing exists
    if [ ! -f "$DOC_ROOT/index.html" ]; then
        echo "<html><body><h1>PageSpeed Envoy Test Server</h1></body></html>" > "$DOC_ROOT/index.html"
    fi
}

generate_envoy_config() {
    log_info "Generating Envoy configuration..."

    local DOC_ROOT="$ENVOY_CONFIG_DIR/www"

    cat > "$ENVOY_CONFIG_FILE" << EOF
# Envoy configuration for PageSpeed filter testing
# Auto-generated by setup_envoy_test.sh

admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: $ENVOY_ADMIN_PORT

static_resources:
  listeners:
    # HTTP listener
    - name: listener_http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: $ENVOY_PORT
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: static_cluster
                          response_headers_to_add:
                            - header:
                                key: "X-Extra-Header"
                                value: "1"
                http_filters:
                  - name: envoy.filters.http.compressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                      response_direction_config:
                        common_config:
                          min_content_length: 100
                          content_type:
                            - "text/html"
                            - "text/css"
                            - "text/plain"
                            - "application/javascript"
                            - "application/json"
                        disable_on_etag_header: false
                      compressor_library:
                        name: text_optimized
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                          memory_level: 5
                          window_bits: 12
                          compression_level: BEST_SPEED
                  - name: envoy.filters.http.pagespeed
                    typed_config:
                      "@type": type.googleapis.com/pagespeed.Decoder
                      key: "x-pagespeed"
                      val: "enabled"
                      # JavaScript library canonicalization for testing.
                      # Format: "size_bytes md5_hash canonical_url"
                      libraries:
                        - "43 1o978_K0_LNE5_ystNklf http://www.modpagespeed.com/rewrite_javascript.js"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    # HTTPS listener
    - name: listener_https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: $ENVOY_HTTPS_PORT
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "$TLS_CERT_FILE"
                    private_key:
                      filename: "$TLS_KEY_FILE"
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_https
                codec_type: AUTO
                route_config:
                  name: local_route_https
                  virtual_hosts:
                    - name: local_service_https
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: static_cluster
                          response_headers_to_add:
                            - header:
                                key: "X-Extra-Header"
                                value: "1"
                http_filters:
                  - name: envoy.filters.http.compressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                      response_direction_config:
                        common_config:
                          min_content_length: 100
                          content_type:
                            - "text/html"
                            - "text/css"
                            - "text/plain"
                            - "application/javascript"
                            - "application/json"
                        disable_on_etag_header: false
                      compressor_library:
                        name: text_optimized
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                          memory_level: 5
                          window_bits: 12
                          compression_level: BEST_SPEED
                  - name: envoy.filters.http.pagespeed
                    typed_config:
                      "@type": type.googleapis.com/pagespeed.Decoder
                      key: "x-pagespeed"
                      val: "enabled"
                      libraries:
                        - "43 1o978_K0_LNE5_ystNklf http://www.modpagespeed.com/rewrite_javascript.js"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: static_cluster
      connect_timeout: 5s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: static_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      # Connect to a simple static file server
                      address: 127.0.0.1
                      port_value: 8081
EOF

    log_info "Configuration written to $ENVOY_CONFIG_FILE"
}

start_static_server() {
    local DOC_ROOT="$ENVOY_CONFIG_DIR/www"
    local STATIC_PID_FILE="$ENVOY_CONFIG_DIR/static.pid"
    local STATIC_SERVER_SCRIPT="$SCRIPT_DIR/static_file_server.py"

    # Check if already running
    if [ -f "$STATIC_PID_FILE" ]; then
        local pid=$(cat "$STATIC_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Static file server already running (PID: $pid)"
            return 0
        fi
    fi

    # Verify the server script exists
    if [ ! -f "$STATIC_SERVER_SCRIPT" ]; then
        log_error "Static file server script not found: $STATIC_SERVER_SCRIPT"
        return 1
    fi

    log_info "Starting static file server on port 8081..."

    # Use setsid to create a new session, detaching from docker compose exec.
    # This ensures the process survives when docker compose exec exits.
    # Use our custom static_file_server.py which supports directory index (index.html).
    setsid python3 "$STATIC_SERVER_SCRIPT" 8081 "$DOC_ROOT" 127.0.0.1 \
        > "$ENVOY_CONFIG_DIR/logs/static.log" 2>&1 &
    local shell_pid=$!

    # Wait a moment for the process to start
    sleep 1

    # Find the actual process PID (nohup may fork)
    local actual_pid
    actual_pid=$(pgrep -f "static_file_server.py 8081" | head -1)
    if [ -n "$actual_pid" ]; then
        echo "$actual_pid" > "$STATIC_PID_FILE"
        log_info "Static file server started (PID: $actual_pid)"
    elif kill -0 "$shell_pid" 2>/dev/null; then
        echo "$shell_pid" > "$STATIC_PID_FILE"
        log_info "Static file server started (PID: $shell_pid)"
    else
        log_error "Failed to start static file server"
        return 1
    fi
}

stop_static_server() {
    local STATIC_PID_FILE="$ENVOY_CONFIG_DIR/static.pid"
    if [ -f "$STATIC_PID_FILE" ]; then
        local pid=$(cat "$STATIC_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Stopping static file server (PID: $pid)..."
            kill "$pid" 2>/dev/null || true
            sleep 0.5
        fi
        rm -f "$STATIC_PID_FILE"
    fi

    # Also kill any remaining static file server processes (fallback)
    local remaining_pids
    remaining_pids=$(pgrep -f "static_file_server.py 8081" 2>/dev/null || true)
    if [ -n "$remaining_pids" ]; then
        log_info "Cleaning up remaining static server processes..."
        pkill -f "static_file_server.py 8081" 2>/dev/null || true
    fi
}

start_envoy() {
    log_info "Starting Envoy..."

    # Stop if running
    stop_envoy_process

    # Start static file server first
    start_static_server || return 1

    # Start Envoy using setsid to create a new session.
    # This is critical when running via 'docker compose exec' - Docker sends
    # SIGTERM to all processes in the exec session when it exits. Using setsid
    # creates a new session (detached from the controlling terminal) so Envoy
    # survives after the setup script and exec session end.
    #
    # Note: We redirect stdout to /dev/null because Envoy logs to --log-path.
    setsid "$ENVOY_BINARY" -c "$ENVOY_CONFIG_FILE" \
        --log-path "$ENVOY_LOG_FILE" \
        --log-level info \
        > /dev/null 2>&1 &

    # Give the process a moment to start
    sleep 1

    # Find the actual Envoy process PID
    local envoy_pid
    envoy_pid=$(pgrep -f "envoy_pagespeed.*$ENVOY_CONFIG_FILE" | head -1)

    if [ -z "$envoy_pid" ]; then
        log_error "Failed to start Envoy - process not found"
        log_info "Checking log file..."
        tail -30 "$ENVOY_LOG_FILE" 2>/dev/null || true
        return 1
    fi

    echo "$envoy_pid" > "$ENVOY_PID_FILE"
    log_info "Envoy started with PID: $envoy_pid"
    log_info "PID file: $ENVOY_PID_FILE"

    # Wait for Envoy to start and be ready to accept connections
    log_info "Waiting for Envoy to be ready..."
    local max_wait=30
    local waited=0
    while [ $waited -lt $max_wait ]; do
        sleep 1
        waited=$((waited + 1))

        # Check if process is still running (use pgrep for reliability)
        if ! pgrep -f "envoy_pagespeed.*$ENVOY_CONFIG_FILE" > /dev/null 2>&1; then
            log_error "Envoy process died during startup"
            log_info "Checking log file..."
            tail -30 "$ENVOY_LOG_FILE" 2>/dev/null || true
            return 1
        fi

        # Check if Envoy is responding
        if curl -s --max-time 2 "http://localhost:$ENVOY_PORT/" > /dev/null 2>&1; then
            log_info "Envoy is responding after ${waited}s"
            break
        fi
    done

    if [ $waited -ge $max_wait ]; then
        log_warn "Envoy may not be fully ready after ${max_wait}s"
    fi

    # Check for PageSpeed header
    if curl -sI "http://localhost:$ENVOY_PORT/mod_pagespeed_example/" 2>/dev/null | grep -qi "X-Page-Speed"; then
        log_info "PageSpeed filter is working!"
    else
        log_warn "PageSpeed header not found (filter may need warm-up)"
    fi

    log_info "Envoy with PageSpeed is running:"
    log_info "  HTTP:  http://localhost:$ENVOY_PORT"
    log_info "  HTTPS: https://localhost:$ENVOY_HTTPS_PORT"
    log_info "  Admin: http://localhost:$ENVOY_ADMIN_PORT"
    log_info "Log file: $ENVOY_LOG_FILE"
    log_info ""
    log_info "Run Python tests with:"
    log_info "  PAGESPEED_SERVER_TYPE=envoy PAGESPEED_PORT=$ENVOY_PORT \\"
    log_info "  PAGESPEED_HTTPS_HOST=localhost PAGESPEED_HTTPS_PORT=$ENVOY_HTTPS_PORT \\"
    log_info "      python3 -m pytest test/system/automatic/test_sanity.py -v"
    log_info ""
    log_info "Or run all tests (including HTTPS):"
    log_info "  ./test/system/run_envoy_tests.sh -v"
}

stop_envoy_process() {
    # First try using PID file
    if [ -f "$ENVOY_PID_FILE" ]; then
        local pid=$(cat "$ENVOY_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Stopping Envoy (PID: $pid)..."
            kill "$pid" 2>/dev/null || true
            sleep 1
        fi
        rm -f "$ENVOY_PID_FILE"
    fi

    # Also kill any remaining envoy_pagespeed processes (fallback)
    local remaining_pids
    remaining_pids=$(pgrep -f "envoy_pagespeed" 2>/dev/null || true)
    if [ -n "$remaining_pids" ]; then
        log_info "Cleaning up remaining Envoy processes..."
        pkill -f "envoy_pagespeed" 2>/dev/null || true
        sleep 1
    fi
}

stop_envoy() {
    stop_envoy_process
    stop_static_server
    log_info "Envoy stopped"
}

show_status() {
    local envoy_running=false
    local static_running=false

    if [ -f "$ENVOY_PID_FILE" ]; then
        local pid=$(cat "$ENVOY_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Envoy is running (PID: $pid)"
            envoy_running=true

            if curl -sI "http://localhost:$ENVOY_PORT/mod_pagespeed_example/" 2>/dev/null | grep -qi "X-Page-Speed"; then
                log_info "PageSpeed filter is active"
            else
                log_warn "PageSpeed header not detected in response"
            fi
        else
            log_info "Envoy is not running (stale PID file)"
        fi
    else
        log_info "Envoy is not running"
    fi

    local STATIC_PID_FILE="$ENVOY_CONFIG_DIR/static.pid"
    if [ -f "$STATIC_PID_FILE" ]; then
        local pid=$(cat "$STATIC_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Static file server is running (PID: $pid)"
            static_running=true
        fi
    fi
}

# Main - only run if not being sourced
# When sourced (e.g., from run_envoy_tests.sh), functions are available
# but commands are not executed automatically
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
case "${1:-start}" in
    start)
        check_binary || exit 1
        setup_directories
        setup_test_content
        generate_tls_certs || exit 1
        generate_envoy_config
        start_envoy
        ;;
    stop)
        stop_envoy
        ;;
    status)
        show_status
        ;;
    restart)
        stop_envoy
        sleep 1
        check_binary || exit 1
        start_envoy
        ;;
    *)
        echo "Usage: $0 [start|stop|status|restart]"
        exit 1
        ;;
esac
fi
